
 --1)

select TOP(1) with ties TOURMAMENTS.NAME AS 'TOURMAMENTS'
from TOURMAMENTS,PARTICIPATIONS,players,TITLES
where TOURMAMENTS.tourmament_id = PARTICIPATIONS.TOURMAMENT_ID and
PARTICIPATIONS.PLAYER_ID = players.PLAYER_ID and
TITLES.TITLE_ID = PLAYERS.TITLE_ID and TITLES.NAME ='IGM'
group by TOURMAMENTS.tourmament_id,TOURMAMENTS.NAME
ORDER BY count(players.PLAYER_ID) DESC






--2)


SELECT TOURMAMENTS.NAME FROM
TOURMAMENTS,
((
SELECT 
TOURMAMENTS.TOURMAMENT_ID
FROM TOURMAMENTS)
 EXCEPT 
(
SELECT TOURMAMENTS.TOURMAMENT_ID
FROM TOURMAMENTS,PARTICIPATIONS,PLAYERS, LOCATIONS
WHERE TOURMAMENTS.TOURMAMENT_ID = PARTICIPATIONS.TOURMAMENT_ID AND
	PARTICIPATIONS.PLAYER_ID = PLAYERS.PLAYER_ID AND
	TOURMAMENTS.LOCATION_ID = LOCATIONS.PLACE_ID AND
		PLAYERS.COUTRY_ID = LOCATIONS.COUNTRY_ID AND
	PARTICIPATIONS.PLACE IN (1,2,3)	
) ) AS T

WHERE TOURMAMENTS.TOURMAMENT_ID =T.TOURMAMENT_ID

	
	
	--3) 	
	select TOURMAMENTS.NAME
	from PARTICIPATIONS, PLAYERS,TOURMAMENTS,
	(select participations.TOURMAMENT_ID as pt1, max (PLAYERS.RATING) as maxrating
	from participations,PLAYERS
	where participations.PLAYER_ID = PLAYERS.PLAYER_ID
	group by participations.TOURMAMENT_ID) as t1,
	
	(select participations.TOURMAMENT_ID as pt2, max (PARTICIPATIONS.PLACE) as maxplace
	from participations
	group by participations.TOURMAMENT_ID) as t2
	where PARTICIPATIONS.PLAYER_ID = PLAYERS.PLAYER_ID and 
	PLAYERS.RATING = t1.maxrating and
	PARTICIPATIONS.place = t2.maxplace and
	t1.pt1 = t2.pt2 and t1.pt1=TOURMAMENTS.TOURMAMENT_ID

	


	
   --4) 

SELECT TOP(3) PLAYERS.NAME as player, (OCKI_1.OCKI + OCKI_2.OCKI) AS 'TOTAL SCORE'
FROM PARTICIPATIONS , PLAYERS,
(
SELECT sum(GAMES.RESULT_FOR_WHITE) AS OCKI,
 GAMES.PLAYER_WHITE_ID as p1
FROM GAMES ,PARTICIPATIONS, TOURMAMENTS 
WHERE TOURMAMENTS.TOURMAMENT_ID = PARTICIPATIONS.TOURMAMENT_ID and
 GAMES.TOURMAMENT_ID=PARTICIPATIONS.TOURMAMENT_ID and
 TOURMAMENTS.NAME ='LIGHTHOUSE INTERSCHOOLS CHESS TOURNAMENT'
GROUP BY GAMES.PLAYER_WHITE_ID
) OCKI_1
,
(SELECT (count(GAMES.PLAYER_BLACK_ID) - sum(GAMES.RESULT_FOR_WHITE)) AS OCKI,
 GAMES.PLAYER_BLACK_ID as p2
FROM GAMES ,PARTICIPATIONS, TOURMAMENTS 
WHERE TOURMAMENTS.TOURMAMENT_ID = PARTICIPATIONS.TOURMAMENT_ID and
 GAMES.TOURMAMENT_ID=PARTICIPATIONS.TOURMAMENT_ID and
 TOURMAMENTS.NAME ='LIGHTHOUSE INTERSCHOOLS CHESS TOURNAMENT'
GROUP BY GAMES.PLAYER_BLACK_ID
) OCKI_2

WHERE OCKI_1.p1 = OCKI_2.p2 AND
OCKI_1.p1 = PARTICIPATIONS.PLAYER_ID AND
PARTICIPATIONS.PLAYER_ID = PLAYERS.PLAYER_ID
ORDER BY 'TOTAL SCORE' DESC


	--5 


	select COUNTRIES.SHORT_NAME as federation, count(PARTICIPATIONS.PLACE)as 'medals'
	from COUNTRIES,PLAYERS, PARTICIPATIONS, TOURMAMENTS
	where COUNTRIES.COUNTRY_ID=PLAYERS.COUTRY_ID and 
	PLAYERS.PLAYER_ID=PARTICIPATIONS.PLAYER_ID and 
	TOURMAMENTS.TOURMAMENT_ID=PARTICIPATIONS.TOURMAMENT_ID and
	TOURMAMENTS.DATE_START > '1999-12-31' and
	PARTICIPATIONS.PLACE in (1,2,3)
	group by COUNTRIES.COUNTRY_ID,COUNTRIES.SHORT_NAME
	order by 'medals' desc



	--6 




	WITH T(A,B) AS (
	select TOP(1) COUNT(GAME_DESCRIPTION.GAME_Id) AS CISLO ,GAME_DESCRIPTION.characteristic_value_id
	from TITLES,PLAYERS,PARTICIPATIONS,
	GAMES,GAME_DESCRIPTION, game_characteristics,characteristics_values
	WHERE TITLES.TITLE_ID=PLAYERS.TITLE_ID AND
	PLAYERS.PLAYER_ID=PARTICIPATIONS.PLAYER_ID AND
	PARTICIPATIONS.TOURMAMENT_ID=GAMES.TOURMAMENT_ID AND
	GAMES.GAME_ID=GAME_DESCRIPTION.GAME_Id AND
	GAME_DESCRIPTION.GAME_characteristic_ID=game_characteristics.game_characteristics_id AND
	GAME_DESCRIPTION.characteristic_value_id=characteristics_values.characteristics_value_id AND
	game_characteristics.game_characteristic_name='opening' AND
	TITLES.NAME='IGM'
	GROUP BY  GAME_DESCRIPTION.characteristic_value_id,GAME_DESCRIPTION.GAME_Id
	ORDER BY CISLO DESC
	)
	SELECT characteristics_values.characteristic_value
	FROM T, characteristics_values
	WHERE T.B = characteristics_values.characteristics_value_id


	


	--7) 



	SELECT TOP(3)  PLAYERS.NAME, PLAYERS.RATING
	FROM PLAYERS, TITLES, GENDERS
	WHERE PLAYERS.TITLE_ID=TITLES.TITLE_ID AND 
	PLAYERS.GENDER_ID=GENDERS.GENDER_ID AND
	PLAYERS.GENDER_ID=2 AND
	  TITLES.TITLE_ID!=1
	ORDER BY PLAYERS.RATING DESC

	
	

	
	
	
	UPDATE CLUBS
	SET   CLUBS.CLUB_NAME = 'DARK HORSE'
	FROM CLUBS
	WHERE CLUBS.CLUB_NAME='FUNKY_MOVES'

	SELECT * FROM CLUBS

	--ÒÎ ÆÅ Ñ ÎØÈÁÊÎÉ (ÐÀÇÌÅÐ)
	UPDATE CLUBS
	SET   CLUBS.CLUB_NAME = 'CHESS_CHESS_CHESS_CHESS_CHESS_CHESS_CHESS_CHESS_CHESS_CHESS_CHESS_'
	FROM CLUBS
	WHERE CLUBS.CLUB_NAME='DARK HORSE'

	SELECT * FROM CLUBS


	--Ageichenko Genadi , LIGHTHOUSE INTERSCHOOLS CHESS TOURNAMENT



	UPDATE GAMES
	SET GAMES.RESULT_FOR_WHITE = 0.0
	FROM GAMES,PARTICIPATIONS,PLAYERS,TOURMAMENTS
	WHERE PLAYERS.PLAYER_ID=PARTICIPATIONS.PLAYER_ID AND
	PARTICIPATIONS.TOURMAMENT_ID=GAMES.TOURMAMENT_ID AND
	TOURMAMENTS.TOURMAMENT_ID=PARTICIPATIONS.TOURMAMENT_ID AND
	PARTICIPATIONS.PLAYER_ID =GAMES.PLAYER_WHITE_ID AND
	GAMES.GAME_ID=9 AND
	 PLAYERS.NAME='Ageichenko Genadi A' 
	AND TOURMAMENTS.NAME='LIGHTHOUSE INTERSCHOOLS CHESS TOURNAMENT'


		SELECT * FROM GAMES

	

	UPDATE GAMES
	SET GAMES.RESULT_FOR_WHITE = -1.0
	FROM GAMES,PARTICIPATIONS,PLAYERS,TOURMAMENTS
	WHERE PLAYERS.PLAYER_ID=PARTICIPATIONS.PLAYER_ID AND
	PARTICIPATIONS.TOURMAMENT_ID=GAMES.TOURMAMENT_ID AND
	TOURMAMENTS.TOURMAMENT_ID=PARTICIPATIONS.TOURMAMENT_ID AND
	PARTICIPATIONS.PLAYER_ID =GAMES.PLAYER_WHITE_ID AND
	GAMES.GAME_ID=9 AND
	 PLAYERS.NAME='Ageichenko Genadi A' 
	AND TOURMAMENTS.NAME='LIGHTHOUSE INTERSCHOOLS CHESS TOURNAMENT'


	-- Ageichenko Genadi  , 'LIGHTHOUSE INTERSCHOOLS CHESS TOURNAMENT'
	
	SELECT * FROM GAMES
	
	DELETE GAMES
	FROM GAMES,PARTICIPATIONS, PLAYERS, TOURMAMENTS
	WHERE PARTICIPATIONS.PLAYER_ID=PLAYERS.PLAYER_ID AND
		PLAYERS.NAME='Ageichenko Genadi A' AND
	TOURMAMENTS.TOURMAMENT_ID=PARTICIPATIONS.TOURMAMENT_ID
	AND TOURMAMENTS.NAME='LIGHTHOUSE INTERSCHOOLS CHESS TOURNAMENT' AND
	(PARTICIPATIONS.PLAYER_ID=GAMES.PLAYER_BLACK_ID OR
	 PARTICIPATIONS.PLAYER_ID=GAMES.PLAYER_WHITE_ID)
	
	SELECT * FROM PARTICIPATIONS

	DELETE PARTICIPATIONS
	FROM PARTICIPATIONS, PLAYERS, TOURMAMENTS
	WHERE PARTICIPATIONS.PLAYER_ID=PLAYERS.PLAYER_ID AND
		PLAYERS.NAME='Ageichenko Genadi A' AND
	TOURMAMENTS.TOURMAMENT_ID=PARTICIPATIONS.TOURMAMENT_ID
	AND TOURMAMENTS.NAME='LIGHTHOUSE INTERSCHOOLS CHESS TOURNAMENT'
	

	
