--неповтор€ющиес€ значени€
set transaction isolation level REPEATABLE READ
BEGIN TRANSACTION
--1
SELECT RATING FROM PLAYERS WHERE PLAYER_ID=5
--4
SELECT RATING FROM PLAYERS WHERE PLAYER_ID=5
COMMIT

