CREATE TABLE [PLAYERS] (
	PLAYER_ID integer NOT NULL,
	NAME varchar NOT NULL,
	SURNAME varchar NOT NULL,
	YEAR_OF_BIRTH integer NOT NULL,
	COUTRY_ID integer NOT NULL,
	GENDER boolean,
	CLUB_ID integer,
  CONSTRAINT [PK_PLAYERS] PRIMARY KEY ( [PLAYER_ID] ASC ) 
)
GO
CREATE TABLE [TOURMAMENTS] (
	TOURMAMENT_ID integer NOT NULL,
	NAME varchar NOT NULL,
	TIME_CONTROL integer NOT NULL,
	PAIRING_SYSTEM integer NOT NULL,
	CHESS_TYPE_ID integer NOT NULL,
	LOCATION integer NOT NULL,
	DATE_START date NOT NULL,
	DATE_END_ID integer NOT NULL,
	GENDER_ID boolean,
  CONSTRAINT [PK_TOURMAMENTS] PRIMARY KEY  (
  [TOURMAMENT_ID] ASC
  ) 

)
GO
CREATE TABLE [LOCATIONS] (
	PLACE_ID integer NOT NULL,
	COUNTRY_ID integer NOT NULL,
	CITY_NAME varchar NOT NULL,
  CONSTRAINT [PK_LOCATIONS] PRIMARY KEY (
  [PLACE_ID] ASC
  )
)
GO
CREATE TABLE [PARTICIPATIONS] (
	TOURMAMENT_ID integer NOT NULL,
	PLAYER_ID integer NOT NULL,
	START_NUMBER integer NOT NULL UNIQUE,
	PLACE integer NOT NULL,
	POINTS integer NOT NULL,
	TIE_BREAKING_SCORE integer NOT NULL,
	GROUP_ID integer NOT NULL,
  CONSTRAINT [PK_PARTICIPATIONS] PRIMARY KEY 
  (
  [TOURMAMENT_ID] ASC
  )
)
GO
CREATE TABLE [PAIRING_SYSTEMS] (
	TYPE_ID integer NOT NULL,
	NAME varchar NOT NULL,
  CONSTRAINT [PK_PAIRING_SYSTEMS] PRIMARY KEY 
  (
  [TYPE_ID] ASC
  ) 
)
GO
CREATE TABLE [GAMES] (
	GAME_ID integer NOT NULL,
	ROUND_NUMBER integer NOT NULL,
	TOURMAMENT_ID integer NOT NULL,
	PLAYER_WHITE_ID integer NOT NULL,
	PLAYER_BLACK_ID integer NOT NULL,
	RESULT_FOR_WHITE float NOT NULL,
	DURATION time NOT NULL,
	DEBUT_ID integer NOT NULL,
  CONSTRAINT [PK_GAMES] PRIMARY KEY 
  (
  [GAME_ID] ASC
  ) 

)
GO
CREATE TABLE [PLAYER_PROGRESS] (
	PLAYER_ID integer NOT NULL,
	DATE_ID integer NOT NULL,
	RATING_STANDART integer NOT NULL,
	RATING_BLITZ integer,
	RATING_RAPID integer,
	TITLE_ID integer,
  CONSTRAINT [PK_PLAYER_PROGRESS] PRIMARY KEY 
  (
  [PLAYER_ID] ASC
  ) 
)
GO
CREATE TABLE [TOURMAMENTS_END_DATES] (
	DATE_ID integer NOT NULL,
	DATE date NOT NULL,
  CONSTRAINT [PK_TOURMAMENTS_END_DATES] PRIMARY KEY 
  (
  [DATE_ID] ASC
  ) 

)
GO
CREATE TABLE [TITLES] (
	TITLE_ID integer NOT NULL,
	NAME varchar NOT NULL,
  CONSTRAINT [PK_TITLES] PRIMARY KEY 
  (
  [TITLE_ID] ASC
  ) 

)
GO
CREATE TABLE [CHESS_TYPES] (
	TYPE_ID integer NOT NULL,
	NAME varchar NOT NULL,
  CONSTRAINT [PK_CHESS_TYPES] PRIMARY KEY 
  (
  [TYPE_ID] ASC
  ) 
)
GO
CREATE TABLE [GENDERS] (
	GENDER_ID boolean NOT NULL,
	NAME varchar NOT NULL,
  CONSTRAINT [PK_GENDERS] PRIMARY KEY 
  (
  [GENDER_ID] ASC
  ) 

)
GO
CREATE TABLE [COUNTRIES] (
	COUNTRY_ID integer NOT NULL,
	COUNTRY_NAME varchar NOT NULL,
	SHORT_NAME varchar NOT NULL,
  CONSTRAINT [PK_COUNTRIES] PRIMARY KEY 
  (
  [COUNTRY_ID] ASC
  )

)
GO
CREATE TABLE [FEDERATION_STATISTICS] (
	TOURMAMENT_ID integer NOT NULL,
	FEDERATION_ID integer NOT NULL UNIQUE,
	GOLD_MEDALS integer NOT NULL,
	SILVER_MEDALS integer NOT NULL,
	BRONZE_MEDALS integer NOT NULL,
  CONSTRAINT [PK_FEDERATION_STATISTICS] PRIMARY KEY 
  (
  [TOURMAMENT_ID] ASC
  ) 

)
GO
CREATE TABLE [TIME_CONTROL] (
	TYPE_ID integer NOT NULL,
	DESCRIPTION varchar NOT NULL,
  CONSTRAINT [PK_TIME_CONTROL] PRIMARY KEY 
  (
  [TYPE_ID] ASC
  ) 

)
GO
CREATE TABLE [CLUBS] (
	CLUB_ID integer NOT NULL,
	CLUB_NAME varchar NOT NULL,
  CONSTRAINT [PK_CLUBS] PRIMARY KEY 
  (
  [CLUB_ID] ASC
  ) 

)
GO
CREATE TABLE [TOURMAMENT_SELECTION] (
	GROUP_ID integer NOT NULL,
	GROUP_NAME integer NOT NULL,
  CONSTRAINT [PK_TOURMAMENT_SELECTION] PRIMARY KEY 
  (
  [GROUP_ID] ASC
  ) 

)
GO
CREATE TABLE [DEBUTS] (
	DEBUT_ID integer NOT NULL,
	DEBUT_NAME varchar NOT NULL,
  CONSTRAINT [PK_DEBUTS] PRIMARY KEY 
  (
  [DEBUT_ID] ASC
  ) 

)
GO
CREATE TABLE [PLAYING_SHEDULE] (
	TOURMAMENT_ID integer NOT NULL,
	ROUND_NUMBER integer NOT NULL,
	DATE_TIME datetime NOT NULL,
  CONSTRAINT [PK_PLAYING_SHEDULE] PRIMARY KEY 
  (
  [TOURMAMENT_ID] ASC
  ) 

)
GO
ALTER TABLE [PLAYERS] WITH CHECK ADD CONSTRAINT [PLAYERS_fk0] FOREIGN KEY ([COUTRY_ID]) REFERENCES [COUNTRIES]([COUNTRY_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PLAYERS] CHECK CONSTRAINT [PLAYERS_fk0]
GO
ALTER TABLE [PLAYERS] WITH CHECK ADD CONSTRAINT [PLAYERS_fk1] FOREIGN KEY ([GENDER]) REFERENCES [GENDERS]([GENDER_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PLAYERS] CHECK CONSTRAINT [PLAYERS_fk1]
GO
ALTER TABLE [PLAYERS] WITH CHECK ADD CONSTRAINT [PLAYERS_fk2] FOREIGN KEY ([CLUB_ID]) REFERENCES [CLUBS]([CLUB_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PLAYERS] CHECK CONSTRAINT [PLAYERS_fk2]
GO

ALTER TABLE [TOURMAMENTS] WITH CHECK ADD CONSTRAINT [TOURMAMENTS_fk0] FOREIGN KEY ([TIME_CONTROL]) REFERENCES [TIME_CONTROL]([TYPE_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [TOURMAMENTS] CHECK CONSTRAINT [TOURMAMENTS_fk0]
GO
ALTER TABLE [TOURMAMENTS] WITH CHECK ADD CONSTRAINT [TOURMAMENTS_fk1] FOREIGN KEY ([PAIRING_SYSTEM]) REFERENCES [PAIRING_SYSTEMS]([TYPE_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [TOURMAMENTS] CHECK CONSTRAINT [TOURMAMENTS_fk1]
GO
ALTER TABLE [TOURMAMENTS] WITH CHECK ADD CONSTRAINT [TOURMAMENTS_fk2] FOREIGN KEY ([CHESS_TYPE_ID]) REFERENCES [CHESS_TYPES]([TYPE_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [TOURMAMENTS] CHECK CONSTRAINT [TOURMAMENTS_fk2]
GO
ALTER TABLE [TOURMAMENTS] WITH CHECK ADD CONSTRAINT [TOURMAMENTS_fk3] FOREIGN KEY ([LOCATION]) REFERENCES [LOCATIONS]([PLACE_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [TOURMAMENTS] CHECK CONSTRAINT [TOURMAMENTS_fk3]
GO
ALTER TABLE [TOURMAMENTS] WITH CHECK ADD CONSTRAINT [TOURMAMENTS_fk4] FOREIGN KEY ([DATE_END_ID]) REFERENCES [TOURMAMENTS_END_DATES]([DATE_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [TOURMAMENTS] CHECK CONSTRAINT [TOURMAMENTS_fk4]
GO
ALTER TABLE [TOURMAMENTS] WITH CHECK ADD CONSTRAINT [TOURMAMENTS_fk5] FOREIGN KEY ([GENDER_ID]) REFERENCES [GENDERS]([GENDER_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [TOURMAMENTS] CHECK CONSTRAINT [TOURMAMENTS_fk5]
GO

ALTER TABLE [LOCATIONS] WITH CHECK ADD CONSTRAINT [LOCATIONS_fk0] FOREIGN KEY ([COUNTRY_ID]) REFERENCES [COUNTRIES]([COUNTRY_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [LOCATIONS] CHECK CONSTRAINT [LOCATIONS_fk0]
GO
ALTER TABLE [LOCATIONS] WITH CHECK ADD CONSTRAINT [LOCATIONS_fk1] FOREIGN KEY ([CITY_NAME]) REFERENCES []([])
ON UPDATE CASCADE
GO
ALTER TABLE [LOCATIONS] CHECK CONSTRAINT [LOCATIONS_fk1]
GO

ALTER TABLE [PARTICIPATIONS] WITH CHECK ADD CONSTRAINT [PARTICIPATIONS_fk0] FOREIGN KEY ([TOURMAMENT_ID]) REFERENCES [TOURMAMENTS]([TOURMAMENT_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PARTICIPATIONS] CHECK CONSTRAINT [PARTICIPATIONS_fk0]
GO
ALTER TABLE [PARTICIPATIONS] WITH CHECK ADD CONSTRAINT [PARTICIPATIONS_fk1] FOREIGN KEY ([PLAYER_ID]) REFERENCES [PLAYERS]([PLAYER_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PARTICIPATIONS] CHECK CONSTRAINT [PARTICIPATIONS_fk1]
GO
ALTER TABLE [PARTICIPATIONS] WITH CHECK ADD CONSTRAINT [PARTICIPATIONS_fk2] FOREIGN KEY ([GROUP_ID]) REFERENCES [TOURMAMENT_SELECTION]([GROUP_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PARTICIPATIONS] CHECK CONSTRAINT [PARTICIPATIONS_fk2]
GO


ALTER TABLE [GAMES] WITH CHECK ADD CONSTRAINT [GAMES_fk0] FOREIGN KEY ([TOURMAMENT_ID]) REFERENCES [TOURMAMENTS]([TOURMAMENT_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [GAMES] CHECK CONSTRAINT [GAMES_fk0]
GO
ALTER TABLE [GAMES] WITH CHECK ADD CONSTRAINT [GAMES_fk1] FOREIGN KEY ([PLAYER_WHITE_ID]) REFERENCES [PLAYERS]([PLAYER_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [GAMES] CHECK CONSTRAINT [GAMES_fk1]
GO
ALTER TABLE [GAMES] WITH CHECK ADD CONSTRAINT [GAMES_fk2] FOREIGN KEY ([PLAYER_BLACK_ID]) REFERENCES [PLAYERS]([PLAYER_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [GAMES] CHECK CONSTRAINT [GAMES_fk2]
GO
ALTER TABLE [GAMES] WITH CHECK ADD CONSTRAINT [GAMES_fk3] FOREIGN KEY ([DEBUT_ID]) REFERENCES [DEBUTS]([DEBUT_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [GAMES] CHECK CONSTRAINT [GAMES_fk3]
GO

ALTER TABLE [PLAYER_PROGRESS] WITH CHECK ADD CONSTRAINT [PLAYER_PROGRESS_fk0] FOREIGN KEY ([PLAYER_ID]) REFERENCES [PLAYERS]([PLAYER_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PLAYER_PROGRESS] CHECK CONSTRAINT [PLAYER_PROGRESS_fk0]
GO
ALTER TABLE [PLAYER_PROGRESS] WITH CHECK ADD CONSTRAINT [PLAYER_PROGRESS_fk1] FOREIGN KEY ([DATE_ID]) REFERENCES [TOURMAMENTS_END_DATES]([DATE_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PLAYER_PROGRESS] CHECK CONSTRAINT [PLAYER_PROGRESS_fk1]
GO
ALTER TABLE [PLAYER_PROGRESS] WITH CHECK ADD CONSTRAINT [PLAYER_PROGRESS_fk2] FOREIGN KEY ([TITLE_ID]) REFERENCES [TITLES]([TITLE_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PLAYER_PROGRESS] CHECK CONSTRAINT [PLAYER_PROGRESS_fk2]
GO






ALTER TABLE [FEDERATION_STATISTICS] WITH CHECK ADD CONSTRAINT [FEDERATION_STATISTICS_fk0] FOREIGN KEY ([TOURMAMENT_ID]) REFERENCES [TOURMAMENTS]([TOURMAMENT_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [FEDERATION_STATISTICS] CHECK CONSTRAINT [FEDERATION_STATISTICS_fk0]
GO
ALTER TABLE [FEDERATION_STATISTICS] WITH CHECK ADD CONSTRAINT [FEDERATION_STATISTICS_fk1] FOREIGN KEY ([FEDERATION_ID]) REFERENCES [COUNTRIES]([COUNTRY_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [FEDERATION_STATISTICS] CHECK CONSTRAINT [FEDERATION_STATISTICS_fk1]
GO





ALTER TABLE [PLAYING_SHEDULE] WITH CHECK ADD CONSTRAINT [PLAYING_SHEDULE_fk0] FOREIGN KEY ([TOURMAMENT_ID]) REFERENCES [TOURMAMENTS]([TOURMAMENT_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PLAYING_SHEDULE] CHECK CONSTRAINT [PLAYING_SHEDULE_fk0]
GO

