USE CHESS_TOURMAMENTS






CREATE TABLE [COUNTRIES] (
	COUNTRY_ID int NOT NULL PRIMARY KEY identity(1,1),
	SHORT_NAME varchar (15) NOT NULL 
	)
GO






CREATE TABLE [GENDERS] (
	GENDER_ID TINYINT NOT NULL PRIMARY KEY identity(1,1),
	NAME varchar(10) NOT NULL,
)
GO





CREATE TABLE [CLUBS] (
	CLUB_ID INT NOT NULL PRIMARY KEY identity(1,1),
	CLUB_NAME nvarchar(40) NOT NULL,
 )
GO





CREATE TABLE [TITLES] (
	TITLE_ID INT NOT NULL PRIMARY KEY identity(1,1),
	NAME varchar(10) NOT NULL,
 )
GO



CREATE TABLE [PAIRING_SYSTEMS] (
	TYPE_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NAME varchar (30) NOT NULL
  )
GO
CREATE TABLE [CHESS_TYPES] (
	TYPE_ID int NOT NULL PRIMARY KEY IDENTITY(1,1),
	NAME varchar(15) NOT NULL,
 )
GO

CREATE TABLE [characteristics_values] (
	characteristics_value_id integer NOT NULL PRIMARY KEY IDENTITY(1,1),
	characteristic_value varchar(50) NOT NULL,
)
GO



CREATE TABLE [game_characteristics] (
	game_characteristics_id integer NOT NULL PRIMARY KEY identity(1,1),
	game_characteristic_name varchar(50) NOT NULL,
 )
GO






CREATE TABLE [LOCATIONS] (
	PLACE_ID int NOT NULL PRIMARY KEY identity(1,1),
	COUNTRY_ID int NOT NULL
		REFERENCES [COUNTRIES] (COUNTRY_ID)
		ON UPDATE CASCADE,
	CITY_NAME varchar(50) NOT NULL,
 )
GO





CREATE TABLE [PLAYERS] (
	PLAYER_ID int NOT NULL PRIMARY KEY identity(1,1),
	NAME varchar (100) NOT NULL,
	YEAR_OF_BIRTH int NOT NULL,
	COUTRY_ID int NOT NULL 
		REFERENCES [COUNTRIES] (COUNTRY_ID)
		ON UPDATE CASCADE,
	GENDER_ID TINYINT NOT NULL
		 REFERENCES GENDERS (GENDER_ID)
		ON UPDATE CASCADE,
	CLUB_ID integer NOT NULL
		REFERENCES CLUBS (CLUB_ID )
		ON UPDATE CASCADE,
	RATING INT,
	TITLE_ID integer NOT NULL
		REFERENCES TITLES (TITLE_ID )	
		ON UPDATE CASCADE,
)
GO




CREATE TABLE [TOURMAMENTS] (
	TOURMAMENT_ID INT NOT NULL  PRIMARY KEY IDENTITY(1,1),
	NAME varchar(60) NOT NULL,
	PAIRING_SYSTEM_ID int NOT NULL
		REFERENCES [PAIRING_SYSTEMS] (TYPE_ID)
		ON UPDATE CASCADE,
	CHESS_TYPE_ID int NOT NULL
		REFERENCES  [CHESS_TYPES] (	TYPE_ID)
		ON UPDATE CASCADE,
	LOCATION_ID int NOT NULL
		REFERENCES [LOCATIONS] (PLACE_ID)
		ON UPDATE CASCADE,
	DATE_START date NOT NULL,
	DATE_END date NOT NULL
  )
GO





ALTER TABLE  [TOURMAMENTS] WITH NOCHECK ADD CONSTRAINT TOURMAMENT_DATES CHECK (DATE_START < =DATE_END) 


CREATE TABLE [PARTICIPATIONS] (
	TOURMAMENT_ID int NOT NULL
		REFERENCES [TOURMAMENTs] (TOURMAMENT_ID)
		ON UPDATE CASCADE,
	PLAYER_ID int NOT NULL
		REFERENCES [PLAYERS] (PLAYER_ID),
	START_NUMBER int NOT NULL,
	PLACE int NOT NULL,
	PARTICIPATION_STATUS BIT,

	PRIMARY KEY (TOURMAMENT_ID, PLAYER_ID)
 )
GO

CREATE TABLE [GAMES] (
	GAME_ID int NOT NULL PRIMARY KEY identity(1,1),
	TOURMAMENT_ID int NOT NULL ,
	PLAYER_WHITE_ID int NOT NULL,
	PLAYER_BLACK_ID int NOT NULL,
	RESULT_FOR_WHITE DECIMAL(2,1) NOT NULL,
	ROUND_NUMBER int NOT NULL ,

	FOREIGN KEY (TOURMAMENT_ID,PLAYER_WHITE_ID) 
	REFERENCES [PARTICIPATIONS] (TOURMAMENT_ID,PLAYER_ID),
	
	FOREIGN KEY (TOURMAMENT_ID,PLAYER_BLACK_ID) 
	REFERENCES [PARTICIPATIONS] (TOURMAMENT_ID,PLAYER_ID)
	
)



ALTER TABLE  [GAMES] ADD CONSTRAINT GAME_RESULT CHECK (RESULT_FOR_WHITE IN (0.5, 0, 1)) 

GO

CREATE TABLE [GAME_DESCRIPTION] (
	GAME_Id integer NOT NULL 
		REFERENCES [GAMES] (GAME_Id)
		ON UPDATE CASCADE,
	GAME_characteristic_ID integer NOT NULL
		REFERENCES [GAME_characteristicS] (GAME_characteristicS_ID)
		ON UPDATE CASCADE,
	characteristic_value_id integer NOT NULL
		REFERENCES  [characteristics_values] (characteristics_value_id)
	    ON UPDATE CASCADE,

		PRIMARY KEY (GAME_Id, GAME_characteristic_ID)
 )
GO







INSERT INTO genders VALUES	( 'NO_GENDER')	;
INSERT INTO genders VALUES	( 'Male')	;
INSERT INTO genders VALUES	('Female')	;



INSERT INTO TITLES VALUES('NO_TITLE')
INSERT INTO TITLES VALUES('IGM')
INSERT INTO TITLES VALUES('IM')
INSERT INTO TITLES VALUES('FM')
INSERT INTO TITLES VALUES('CM')
INSERT INTO TITLES VALUES('NM')
INSERT INTO TITLES VALUES('WIM')




INSERT INTO COUNTRIES VALUES('No country')
INSERT INTO COUNTRIES VALUES('AFG')
INSERT INTO COUNTRIES VALUES('AHO')
INSERT INTO COUNTRIES VALUES('ALB')
INSERT INTO COUNTRIES VALUES('ALG')
INSERT INTO COUNTRIES VALUES('AND')
INSERT INTO COUNTRIES VALUES('ANG')
INSERT INTO COUNTRIES VALUES('BDI')
INSERT INTO COUNTRIES VALUES('BEL')
INSERT INTO COUNTRIES VALUES('Bgld')
INSERT INTO COUNTRIES VALUES('BHU')
INSERT INTO COUNTRIES VALUES('BIH')
INSERT INTO COUNTRIES VALUES('BLR')
INSERT INTO COUNTRIES VALUES('BOL')
INSERT INTO COUNTRIES VALUES('CAT')
INSERT INTO COUNTRIES VALUES('CHI')
INSERT INTO COUNTRIES VALUES('CHN')
INSERT INTO COUNTRIES VALUES('CIV')
INSERT INTO COUNTRIES VALUES('CMR')
INSERT INTO COUNTRIES VALUES('COL')
INSERT INTO COUNTRIES VALUES('DOM')
INSERT INTO COUNTRIES VALUES('ECU')
INSERT INTO COUNTRIES VALUES('EGY')
INSERT INTO COUNTRIES VALUES('ENG')
INSERT INTO COUNTRIES VALUES('ESA')
INSERT INTO COUNTRIES VALUES('ESP')
INSERT INTO COUNTRIES VALUES('GAM')
INSERT INTO COUNTRIES VALUES('GCI')
INSERT INTO COUNTRIES VALUES('GEO')
INSERT INTO COUNTRIES VALUES('GER')
INSERT INTO COUNTRIES VALUES('GHA')
INSERT INTO COUNTRIES VALUES('GRE')
INSERT INTO COUNTRIES VALUES('IND')
INSERT INTO COUNTRIES VALUES('IRI')
INSERT INTO COUNTRIES VALUES('IRL')
INSERT INTO COUNTRIES VALUES('IRQ')
INSERT INTO COUNTRIES VALUES('ISL')
INSERT INTO COUNTRIES VALUES('ISR')
INSERT INTO COUNTRIES VALUES('KAZ')
INSERT INTO COUNTRIES VALUES('KEN')
INSERT INTO COUNTRIES VALUES('KGZ')
INSERT INTO COUNTRIES VALUES('KOR')
INSERT INTO COUNTRIES VALUES('KOS')
INSERT INTO COUNTRIES VALUES('KSA')
INSERT INTO COUNTRIES VALUES('LIE')
INSERT INTO COUNTRIES VALUES('LTU')
INSERT INTO COUNTRIES VALUES('LUX')
INSERT INTO COUNTRIES VALUES('MAC')
INSERT INTO COUNTRIES VALUES('MAD')
INSERT INTO COUNTRIES VALUES('MAR')
INSERT INTO COUNTRIES VALUES('MLT')
INSERT INTO COUNTRIES VALUES('MNC')
INSERT INTO COUNTRIES VALUES('MNE')
INSERT INTO COUNTRIES VALUES('MOZ')
INSERT INTO COUNTRIES VALUES('MRI')
INSERT INTO COUNTRIES VALUES('MTN')
INSERT INTO COUNTRIES VALUES('NO')
INSERT INTO COUNTRIES VALUES('NZL')
INSERT INTO COUNTRIES VALUES('OMA')
INSERT INTO COUNTRIES VALUES('PAK')
INSERT INTO COUNTRIES VALUES('PAN')
INSERT INTO COUNTRIES VALUES('PAR')
INSERT INTO COUNTRIES VALUES('PER')
INSERT INTO COUNTRIES VALUES('QAT')
INSERT INTO COUNTRIES VALUES('ROU')
INSERT INTO COUNTRIES VALUES('RSA')
INSERT INTO COUNTRIES VALUES('RUS')
INSERT INTO COUNTRIES VALUES('RWA')
INSERT INTO COUNTRIES VALUES('Sbg')
INSERT INTO COUNTRIES VALUES('SCG')
INSERT INTO COUNTRIES VALUES('SUD')
INSERT INTO COUNTRIES VALUES('SUI')
INSERT INTO COUNTRIES VALUES('SUR')
INSERT INTO COUNTRIES VALUES('SVK')
INSERT INTO COUNTRIES VALUES('SWE')
INSERT INTO COUNTRIES VALUES('SWZ')
INSERT INTO COUNTRIES VALUES('Tirol')
INSERT INTO COUNTRIES VALUES('TTO')
INSERT INTO COUNTRIES VALUES('TUN')
INSERT INTO COUNTRIES VALUES('TUR')
INSERT INTO COUNTRIES VALUES('UAE')
INSERT INTO COUNTRIES VALUES('UGA')
INSERT INTO COUNTRIES VALUES('UKR')
INSERT INTO COUNTRIES VALUES('Vbg')
INSERT INTO COUNTRIES VALUES('ZAM')
INSERT INTO COUNTRIES VALUES('ZIM')
INSERT INTO COUNTRIES VALUES('USA')






INSERT INTO CLUBS VALUES('NO_CLUB')
INSERT INTO CLUBS VALUES('Zombie Bliss')
INSERT INTO CLUBS VALUES('FUNKY_MOVES')
INSERT INTO CLUBS VALUES('1000-1500 Club')
INSERT INTO CLUBS VALUES('600-1500 CLUB')
INSERT INTO CLUBS VALUES('A Bit More Chess')
INSERT INTO CLUBS VALUES('Abandoned')
INSERT INTO CLUBS VALUES('Analysis')
INSERT INTO CLUBS VALUES('ANIMAL FARM')
INSERT INTO CLUBS VALUES('ANIMALS')
INSERT INTO CLUBS VALUES('Anti - Racism Club')
INSERT INTO CLUBS VALUES('Ars Technica')
INSERT INTO CLUBS VALUES('Arsenal Football Club Appreci.')
INSERT INTO CLUBS VALUES('artistry')
INSERT INTO CLUBS VALUES('Asian Chess Club')
INSERT INTO CLUBS VALUES('ATHEIST Club')
INSERT INTO CLUBS VALUES('Attention Whales')
INSERT INTO CLUBS VALUES('Baby Seal Club')
INSERT INTO CLUBS VALUES('Baby Seal Club')
INSERT INTO CLUBS VALUES('Bang Average')
INSERT INTO CLUBS VALUES('BDG')
INSERT INTO CLUBS VALUES('Blade Chess')
INSERT INTO CLUBS VALUES('Brasil Club!')
INSERT INTO CLUBS VALUES('Camelot Oasis in Space')
INSERT INTO CLUBS VALUES('Canadian Club')
INSERT INTO CLUBS VALUES('Cats on Mars!')
INSERT INTO CLUBS VALUES('Chelsea FC Club')
INSERT INTO CLUBS VALUES('Chess Club')
INSERT INTO CLUBS VALUES('Chess Players (CMS)')
INSERT INTO CLUBS VALUES('Chess Warriors Club')
INSERT INTO CLUBS VALUES('Chessaroos Australia')
INSERT INTO CLUBS VALUES('Christian Rock Fans')
INSERT INTO CLUBS VALUES('Cinematic Chess Club')
INSERT INTO CLUBS VALUES('Club Africa')
INSERT INTO CLUBS VALUES('Club Asia')
INSERT INTO CLUBS VALUES('Club classic rock')
INSERT INTO CLUBS VALUES('CLUB COLORADO USA')
INSERT INTO CLUBS VALUES('Club Sandwich')
INSERT INTO CLUBS VALUES('club scene')
INSERT INTO CLUBS VALUES('CLUBE BRASIL')
INSERT INTO CLUBS VALUES('CPFC BBS')
INSERT INTO CLUBS VALUES('CPU (Chess Players United) CL.')
INSERT INTO CLUBS VALUES('Danish Club')
INSERT INTO CLUBS VALUES('Echecs!')
INSERT INTO CLUBS VALUES('English Speakers')
INSERT INTO CLUBS VALUES('Epidemic')
INSERT INTO CLUBS VALUES('eUK National Chess Team')
INSERT INTO CLUBS VALUES('FanFicFans')
INSERT INTO CLUBS VALUES('Fly a Rebel Flag Chess Club')
INSERT INTO CLUBS VALUES('Football Fans Club')
INSERT INTO CLUBS VALUES('FRANCE')
INSERT INTO CLUBS VALUES('Friends Of Cash')
INSERT INTO CLUBS VALUES('Galaxy Club')
INSERT INTO CLUBS VALUES('Gambit Fantasy')
INSERT INTO CLUBS VALUES('GRANDMASTER DREAMERS')
INSERT INTO CLUBS VALUES('Here on Earth')
INSERT INTO CLUBS VALUES('High School Chess Players')
INSERT INTO CLUBS VALUES('Ibarselona!')
INSERT INTO CLUBS VALUES('II cavaliere oscuro')
INSERT INTO CLUBS VALUES('INDIAN CLUB')
INSERT INTO CLUBS VALUES('Infinite R3versal')
INSERT INTO CLUBS VALUES('International Chess Group')
INSERT INTO CLUBS VALUES('ISCABBS')
INSERT INTO CLUBS VALUES('Junior Players Prowess')
INSERT INTO CLUBS VALUES('Kabayan')
INSERT INTO CLUBS VALUES('KJ Crew')
INSERT INTO CLUBS VALUES('LOS ANDES')
INSERT INTO CLUBS VALUES('Manchester United')
INSERT INTO CLUBS VALUES('Maybe Masters ?')
INSERT INTO CLUBS VALUES('McClub')
INSERT INTO CLUBS VALUES('MetalKca')
INSERT INTO CLUBS VALUES('Monty Python Club')
INSERT INTO CLUBS VALUES('Music!')
INSERT INTO CLUBS VALUES('MUTI')
INSERT INTO CLUBS VALUES('New Jersey Pawn Pushers')
INSERT INTO CLUBS VALUES('Nonngraded Tournaments')
INSERT INTO CLUBS VALUES('Norgesgl asset')
INSERT INTO CLUBS VALUES('North American Chess Club')
INSERT INTO CLUBS VALUES('North American Chess Club')
INSERT INTO CLUBS VALUES('OTB Chess Players')
INSERT INTO CLUBS VALUES('PCs were made for Chess1')
INSERT INTO CLUBS VALUES('Personal Chess Training')
INSERT INTO CLUBS VALUES('Philosophia')
INSERT INTO CLUBS VALUES('Popeye')
INSERT INTO CLUBS VALUES('Popeye The Sailor Man CLUB')
INSERT INTO CLUBS VALUES('Portugal')
INSERT INTO CLUBS VALUES('Portuguese Speakers')
INSERT INTO CLUBS VALUES('Private Chess Club')
INSERT INTO CLUBS VALUES('protect animals')
INSERT INTO CLUBS VALUES('Provisional Club!')
INSERT INTO CLUBS VALUES('Quintana del Puente')
INSERT INTO CLUBS VALUES('RHP Beta testers club')
INSERT INTO CLUBS VALUES('RHP International Club')
INSERT INTO CLUBS VALUES('Robert Jarr.es Fischer Club')
INSERT INTO CLUBS VALUES('Scacchisti Italiani')
INSERT INTO CLUBS VALUES('Science Fiction Club')
INSERT INTO CLUBS VALUES('Scotland Club')
INSERT INTO CLUBS VALUES('SLOVENIJA')
INSERT INTO CLUBS VALUES('Small Group Tournament Chess...')
INSERT INTO CLUBS VALUES('Smiffys Pav/n Stars')
INSERT INTO CLUBS VALUES('Something Awful Chess Club')
INSERT INTO CLUBS VALUES('STARWARS CLUB')
INSERT INTO CLUBS VALUES('Stat SA Chess Club')
INSERT INTO CLUBS VALUES('Super Terrific Funtime Chess .')
INSERT INTO CLUBS VALUES('Superstars')
INSERT INTO CLUBS VALUES('t Hoofts Knights')
INSERT INTO CLUBS VALUES('The Active Club Kinetic (TACK...')
INSERT INTO CLUBS VALUES('The Bankers')
INSERT INTO CLUBS VALUES('The Beginners Club')
INSERT INTO CLUBS VALUES('The Best Club In The World')
INSERT INTO CLUBS VALUES('The Canceled Checks')
INSERT INTO CLUBS VALUES('The Cats Whiskers')
INSERT INTO CLUBS VALUES('The Christian Chess Club')
INSERT INTO CLUBS VALUES('The Dark Tower')
INSERT INTO CLUBS VALUES('The Dog House')
INSERT INTO CLUBS VALUES('The fast movers')
INSERT INTO CLUBS VALUES('The Flying Aces')
INSERT INTO CLUBS VALUES('The Grateful Dead')
INSERT INTO CLUBS VALUES('The Jazz Club')
INSERT INTO CLUBS VALUES('The Kings Gambiteers')
INSERT INTO CLUBS VALUES('The Kiwi Club')
INSERT INTO CLUBS VALUES('The Lone Star Club')
INSERT INTO CLUBS VALUES('The NHL Hockey Fan Club')
INSERT INTO CLUBS VALUES('the nike club')
INSERT INTO CLUBS VALUES('The patriots')
INSERT INTO CLUBS VALUES('The Poker Players Club')
INSERT INTO CLUBS VALUES('The Reckless Players')
INSERT INTO CLUBS VALUES('The Samurai Club')
INSERT INTO CLUBS VALUES('THE SPANISH INQUISITION')
INSERT INTO CLUBS VALUES('the Swedish clan clubb')
INSERT INTO CLUBS VALUES('The Tao of Chess')
INSERT INTO CLUBS VALUES('The Worldwide Club')
INSERT INTO CLUBS VALUES('Tottenham Hotspur')
INSERT INTO CLUBS VALUES('Toumoi HFR')
INSERT INTO CLUBS VALUES('Tournaments On Demand!')
INSERT INTO CLUBS VALUES('TSM')
INSERT INTO CLUBS VALUES('Under 1000 Club')
INSERT INTO CLUBS VALUES('university chess club')
INSERT INTO CLUBS VALUES('Wesco Chess')
INSERT INTO CLUBS VALUES('World Wide Chess Club')
INSERT INTO CLUBS VALUES('BACK in the USSR')




INSERT INTO [CHESS_TYPES] VALUES('STANDART')
INSERT INTO [CHESS_TYPES] VALUES('RAPID')
INSERT INTO [CHESS_TYPES] VALUES('BLITZ')



INSERT INTO [PAIRING_SYSTEMS] VALUES('Swiss-system')
INSERT INTO [PAIRING_SYSTEMS] VALUES('Round-robin')
INSERT INTO [PAIRING_SYSTEMS] VALUES('Olympic_system')




INSERT INTO [game_characteristics] VALUES('opening')
INSERT INTO [game_characteristics] VALUES('middlegame')
INSERT INTO [game_characteristics] VALUES('endgame')





INSERT INTO [characteristics_values] VALUES('NO_characteristics_value')
INSERT INTO [characteristics_values] VALUES('Английское начало')
INSERT INTO [characteristics_values] VALUES('Атака Гроба')
INSERT INTO [characteristics_values] VALUES('Атака Лолли')
INSERT INTO [characteristics_values] VALUES('Атака Макса Ланге')
INSERT INTO [characteristics_values] VALUES('Атака Парэма')
INSERT INTO [characteristics_values] VALUES('Атака Тромповского')
INSERT INTO [characteristics_values] VALUES('Атака Фегателло')
INSERT INTO [characteristics_values] VALUES('Белградский гамбит')
INSERT INTO [characteristics_values] VALUES('Будапештский гамбит')
INSERT INTO [characteristics_values] VALUES('Вариант Алапина')
INSERT INTO [characteristics_values] VALUES('Вариант дракона')
INSERT INTO [characteristics_values] VALUES('Вариант Найдорфа')
INSERT INTO [characteristics_values] VALUES('Вариант отравленной пешки')
INSERT INTO [characteristics_values] VALUES('Вариант Полугаевского')
INSERT INTO [characteristics_values] VALUES('Вариант Ульвестада')
INSERT INTO [characteristics_values] VALUES('Вариант Фрица')
INSERT INTO [characteristics_values] VALUES('Вариант Чигорина')
INSERT INTO [characteristics_values] VALUES('Венгерская партия')
INSERT INTO [characteristics_values] VALUES('Венская партия')
INSERT INTO [characteristics_values] VALUES('Волжский гамбит')
INSERT INTO [characteristics_values] VALUES('Гамбит Альгайера')
INSERT INTO [characteristics_values] VALUES('Гамбит Бледова')
INSERT INTO [characteristics_values] VALUES('Гамбит Блэкберна')
INSERT INTO [characteristics_values] VALUES('Гамбит Блэкмара — Димера')
INSERT INTO [characteristics_values] VALUES('Гамбит Блюменфельда')
INSERT INTO [characteristics_values] VALUES('Гамбит Брейера')
INSERT INTO [characteristics_values] VALUES('Гамбит Вагнера')
INSERT INTO [characteristics_values] VALUES('Гамбит Гампе — Альгайера')
INSERT INTO [characteristics_values] VALUES('Гамбит Ганштейна')
INSERT INTO [characteristics_values] VALUES('Гамбит Гёринга')
INSERT INTO [characteristics_values] VALUES('Гамбит Герцфельда')
INSERT INTO [characteristics_values] VALUES('Гамбит Греко — Филидора')
INSERT INTO [characteristics_values] VALUES('Гамбит Греко (дебют слона)')
INSERT INTO [characteristics_values] VALUES('Гамбит Греко (итальянская партия)')
INSERT INTO [characteristics_values] VALUES('Гамбит Гулам Кассима')
INSERT INTO [characteristics_values] VALUES('Гамбит Джерома')
INSERT INTO [characteristics_values] VALUES('Гамбит Зильбершмидта')
INSERT INTO [characteristics_values] VALUES('Гамбит Каннингема')
INSERT INTO [characteristics_values] VALUES('Гамбит Каспарова')
INSERT INTO [characteristics_values] VALUES('Гамбит Квааде')
INSERT INTO [characteristics_values] VALUES('Гамбит Кизерицкого')
INSERT INTO [characteristics_values] VALUES('Гамбит коня')
INSERT INTO [characteristics_values] VALUES('Гамбит Кохрена (принятый королевский гамбит)')
INSERT INTO [characteristics_values] VALUES('Гамбит Кохрена (русская партия)')
INSERT INTO [characteristics_values] VALUES('Гамбит Крейчика')
INSERT INTO [characteristics_values] VALUES('Гамбит Лисицына')
INSERT INTO [characteristics_values] VALUES('Гамбит Лолли')
INSERT INTO [characteristics_values] VALUES('Гамбит Льюиса')
INSERT INTO [characteristics_values] VALUES('Гамбит Мак-Доннелла')
INSERT INTO [characteristics_values] VALUES('Гамбит Морра')
INSERT INTO [characteristics_values] VALUES('Гамбит Муцио')
INSERT INTO [characteristics_values] VALUES('Гамбит Петрова')
INSERT INTO [characteristics_values] VALUES('Гамбит Пирса')
INSERT INTO [characteristics_values] VALUES('Гамбит Понциани')
INSERT INTO [characteristics_values] VALUES('Гамбит Райса')
INSERT INTO [characteristics_values] VALUES('Гамбит Розентретера')
INSERT INTO [characteristics_values] VALUES('Гамбит Рубинштейна')
INSERT INTO [characteristics_values] VALUES('Гамбит Руссо')
INSERT INTO [characteristics_values] VALUES('Гамбит Сальвио')
INSERT INTO [characteristics_values] VALUES('Гамбит слона')
INSERT INTO [characteristics_values] VALUES('Гамбит Стаунтона')
INSERT INTO [characteristics_values] VALUES('Гамбит Стейница')
INSERT INTO [characteristics_values] VALUES('Гамбит Тарраша')
INSERT INTO [characteristics_values] VALUES('Гамбит Урусова')
INSERT INTO [characteristics_values] VALUES('Гамбит Фрома')
INSERT INTO [characteristics_values] VALUES('Гамбит Хэллоуин')
INSERT INTO [characteristics_values] VALUES('Гамбит Шара — Геннига')
INSERT INTO [characteristics_values] VALUES('Гамбит Эванса')
INSERT INTO [characteristics_values] VALUES('Гамбит Энглунда')
INSERT INTO [characteristics_values] VALUES('Гамбит Яниша')
INSERT INTO [characteristics_values] VALUES('Голландская защита')
INSERT INTO [characteristics_values] VALUES('Голландский гамбит')
INSERT INTO [characteristics_values] VALUES('Двойной гамбит Мак-Доннелла')
INSERT INTO [characteristics_values] VALUES('Дебют Алапина')
INSERT INTO [characteristics_values] VALUES('Дебют Андерсена')
INSERT INTO [characteristics_values] VALUES('Дебют Берда')
INSERT INTO [characteristics_values] VALUES('Дебют ван Круйса')
INSERT INTO [characteristics_values] VALUES('Дебют Клеменца')
INSERT INTO [characteristics_values] VALUES('Дебют Константинопольского')
INSERT INTO [characteristics_values] VALUES('Дебют королевского коня')
INSERT INTO [characteristics_values] VALUES('Дебют Ларсена')
INSERT INTO [characteristics_values] VALUES('Дебют Мизеса')
INSERT INTO [characteristics_values] VALUES('Дебют Наполеона')
INSERT INTO [characteristics_values] VALUES('Дебют Нимцовича')
INSERT INTO [characteristics_values] VALUES('Дебют Понциани')
INSERT INTO [characteristics_values] VALUES('Дебют Рети')
INSERT INTO [characteristics_values] VALUES('Дебют слона')
INSERT INTO [characteristics_values] VALUES('Дебют Сокольского')
INSERT INTO [characteristics_values] VALUES('Дебют трёх коней')
INSERT INTO [characteristics_values] VALUES('Дебют ферзевой пешки')
INSERT INTO [characteristics_values] VALUES('Дебют ферзевых пешек')
INSERT INTO [characteristics_values] VALUES('Дебют четырёх коней')
INSERT INTO [characteristics_values] VALUES('Защита Алехина')
INSERT INTO [characteristics_values] VALUES('Защита Беккера')
INSERT INTO [characteristics_values] VALUES('Защита Бенони')
INSERT INTO [characteristics_values] VALUES('Защита Боголюбова')
INSERT INTO [characteristics_values] VALUES('Защита Греко')
INSERT INTO [characteristics_values] VALUES('Защита Грюнфельда')
INSERT INTO [characteristics_values] VALUES('Защита Гундерама')
INSERT INTO [characteristics_values] VALUES('Защита Дамиано')
INSERT INTO [characteristics_values] VALUES('Защита двух коней')
INSERT INTO [characteristics_values] VALUES('Защита Каро-Канн')
INSERT INTO [characteristics_values] VALUES('Защита Нимцовича')
INSERT INTO [characteristics_values] VALUES('Защита Оуэна')
INSERT INTO [characteristics_values] VALUES('Защита Пирца — Уфимцева')
INSERT INTO [characteristics_values] VALUES('Защита Рагозина')
INSERT INTO [characteristics_values] VALUES('Защита Робача')
INSERT INTO [characteristics_values] VALUES('Защита Святого Георгия')
INSERT INTO [characteristics_values] VALUES('Защита Тарраша')
INSERT INTO [characteristics_values] VALUES('Защита Филидора')
INSERT INTO [characteristics_values] VALUES('Защита Фишера')
INSERT INTO [characteristics_values] VALUES('Защита Чигорина')
INSERT INTO [characteristics_values] VALUES('Защита Шаллопа')
INSERT INTO [characteristics_values] VALUES('Индийская защита')
INSERT INTO [characteristics_values] VALUES('Испанская партия')
INSERT INTO [characteristics_values] VALUES('Итальянская партия')
INSERT INTO [characteristics_values] VALUES('Каталонское начало')
INSERT INTO [characteristics_values] VALUES('Контратака Тракслера')
INSERT INTO [characteristics_values] VALUES('Контргамбит Альбина')
INSERT INTO [characteristics_values] VALUES('Контргамбит Винавера')
INSERT INTO [characteristics_values] VALUES('Контргамбит Нимцовича')
INSERT INTO [characteristics_values] VALUES('Контргамбит Фалькбеера')
INSERT INTO [characteristics_values] VALUES('Королевский гамбит')
INSERT INTO [characteristics_values] VALUES('Латышский гамбит')
INSERT INTO [characteristics_values] VALUES('Лондонская система')
INSERT INTO [characteristics_values] VALUES('Львовский гамбит')
INSERT INTO [characteristics_values] VALUES('Новоиндийская защита')
INSERT INTO [characteristics_values] VALUES('Отказанный королевский гамбит')
INSERT INTO [characteristics_values] VALUES('Отказанный ферзевый гамбит')
INSERT INTO [characteristics_values] VALUES('Перуанский гамбит')
INSERT INTO [characteristics_values] VALUES('Польская защита')
INSERT INTO [characteristics_values] VALUES('Польский гамбит')
INSERT INTO [characteristics_values] VALUES('Принятый королевский гамбит')
INSERT INTO [characteristics_values] VALUES('Принятый ферзевый гамбит')
INSERT INTO [characteristics_values] VALUES('Русская партия')
INSERT INTO [characteristics_values] VALUES('Сарагосское начало')
INSERT INTO [characteristics_values] VALUES('Северный гамбит')
INSERT INTO [characteristics_values] VALUES('Система Вересова')
INSERT INTO [characteristics_values] VALUES('Система Левитского')
INSERT INTO [characteristics_values] VALUES('Система Нимцовича')
INSERT INTO [characteristics_values] VALUES('Система Стейница')
INSERT INTO [characteristics_values] VALUES('Сицилианская защита')
INSERT INTO [characteristics_values] VALUES('Сицилианский гамбит')
INSERT INTO [characteristics_values] VALUES('Скандинавская защита')
INSERT INTO [characteristics_values] VALUES('Славянская защита')
INSERT INTO [characteristics_values] VALUES('Славянский гамбит')
INSERT INTO [characteristics_values] VALUES('Староиндийская защита')
INSERT INTO [characteristics_values] VALUES('Староиндийское начало')
INSERT INTO [characteristics_values] VALUES('Схевенингенский вариант')
INSERT INTO [characteristics_values] VALUES('Ферзевый гамбит')
INSERT INTO [characteristics_values] VALUES('Французская защита')
INSERT INTO [characteristics_values] VALUES('Центральный дебют')
INSERT INTO [characteristics_values] VALUES('Центральный контргамбит')
INSERT INTO [characteristics_values] VALUES('Челябинский вариант')
INSERT INTO [characteristics_values] VALUES('Швейцарский гамбит')
INSERT INTO [characteristics_values] VALUES('Шотландская партия')
INSERT INTO [characteristics_values] VALUES('Шотландский гамбит')




INSERT INTO [characteristics_values] VALUES ('Борьба за центр')
INSERT INTO [characteristics_values] VALUES ('Борьба за открытые линии')
INSERT INTO [characteristics_values] VALUES ('Создание у противника слабостей') 
 


 
INSERT INTO [characteristics_values] VALUES ('Двухфигурный эндшпиль')
INSERT INTO [characteristics_values] VALUES ('Трёхфигурный эндшпиль')
INSERT INTO [characteristics_values] VALUES ('Король и пешка против короля')
INSERT INTO [characteristics_values] VALUES ('Три фигуры против одной')
INSERT INTO [characteristics_values] VALUES ('Две фигуры против двух')
INSERT INTO [characteristics_values] VALUES ('Другое')




INSERT INTO [LOCATIONS] VALUES 	(66,	'NO_LOCATION')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Архан гельское')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Белоомут ')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Вербилки')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Верея')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Абрамцево')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Алабино')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Апрелевка')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Ашитково')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Байконур')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Бакшеево')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Балашиха')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Барыбино')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Белозёрский')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Белые Столбы')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Бородино (Московская обл.)')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Бронницы')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Быково (Московская обл.)')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Валуево')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Видное')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Внуково')
INSERT INTO [LOCATIONS] VALUES 	(66,	'Москва')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Wellen ')
INSERT INTO [LOCATIONS] VALUES 	(29,	' Libin' )
INSERT INTO [LOCATIONS] VALUES 	(29,	'Zonhoven')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Andenne')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Anhe')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Anion')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Aubange')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Bastogne')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Bertrix')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Bouillon')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Cenfontaine')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Chiny')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Durbuy')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Etalle')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Florenville')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Habay')
INSERT INTO [LOCATIONS] VALUES 	(29,	'La RochG-en-Ardenne')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Lglise')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Manhay')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Marche-en-FamennG')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Messancy')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Rendeux')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Tellin')
INSERT INTO [LOCATIONS] VALUES 	(29,	'TennGvillG')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Tintigny')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Vinton')
INSERT INTO [LOCATIONS] VALUES 	(29,	'Wellin')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Newport')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Portsmouth')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Rye')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Absecon')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Allentown')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Alpine')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Asbury Park')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Asbury')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Atlantic City')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Atlantic Highlands')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Avalon')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Avenel')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Basking Ridge')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Bayonne')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Beach Haven')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Bedminster')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Belle Mead')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Belmar')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Berlin')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Bernards')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Bloomfield')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Bloomingdale')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Bogota')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Salem')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'West Lebanon')
INSERT INTO [LOCATIONS] VALUES 	(86 ,	'Wolfeboro')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Feltham')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Greenford')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Hampton')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Harrow')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Hayes')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Hornchurch')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Hounslow')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Ilford')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Isleworth')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Kingston Upon Thames')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'London')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Northolt')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Northwood')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Orpington')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Pinner')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Purley')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Richmond')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Romford')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'South Croydon')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Southall')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Stanmore')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Surbiton')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Sutton')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Twickenham')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Uxbridge')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Welling')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Wembley')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'West Wickham')
INSERT INTO [LOCATIONS] VALUES 	(23 ,	'Westerham')



INSERT INTO PLAYERS VALUES  ('Afanasiev Vadim',	1995	,	82	,	1	,	52	,	2124	,	3	)
INSERT INTO PLAYERS VALUES  ('Ageichenko Genadi A',	1942	,	36	,	1	,	29	,	2158	,	7	)
INSERT INTO PLAYERS VALUES  ('Apryshko Gleb',	2009	,	59	,	1	,	41	,	2417	,	4	)
INSERT INTO PLAYERS VALUES  ('Arbuzov Timofey',	1954	,	81	,	1	,	69	,	1749	,	6	)
INSERT INTO PLAYERS VALUES  ('Arkhipenko Daniil',	1980	,	25	,	1	,	40	,	2173	,	7	)
INSERT INTO PLAYERS VALUES  ('Babaian Eduard',	1937	,	83	,	1	,	96	,	1929	,	5	)
INSERT INTO PLAYERS VALUES  ('Berezhkov Andrey',	2004	,	26	,	1	,	138	,	2236	,	3	)
INSERT INTO PLAYERS VALUES  ('Buniatyan David',	1955	,	78	,	1	,	59	,	1704	,	2	)
INSERT INTO PLAYERS VALUES  ('Chumachenko Alexander',	1949	,	67	,	1	,	78	,	2126	,	7	)
INSERT INTO PLAYERS VALUES  ('Davydova Kira',	2005	,	49	,	2	,	93	,	1789	,	7	)
INSERT INTO PLAYERS VALUES  ('Dragomarezkij Evgeni',	1949	,	31	,	1	,	26	,	2431	,	1	)
INSERT INTO PLAYERS VALUES  ('Fetisenkov Vadim',	1977	,	19	,	1	,	17	,	2092	,	7	)
INSERT INTO PLAYERS VALUES  ('Gasparian Karen',	1953	,	50	,	2	,	49	,	1978	,	1	)
INSERT INTO PLAYERS VALUES  ('Gorbatov Alexej',	1951	,	56	,	1	,	70	,	2181	,	6	)
INSERT INTO PLAYERS VALUES  ('Kasaeva Sofiia',	2009	,	28	,	2	,	81	,	1456	,	6	)
INSERT INTO PLAYERS VALUES  ('Katvalyan A.',	1985	,	57	,	2	,	63	,	1801	,	1	)
INSERT INTO PLAYERS VALUES  ('Kolmakov Pavel',	1962	,	59	,	1	,	100	,	2177	,	3	)
INSERT INTO PLAYERS VALUES  ('Krupnova Anna',	1977	,	55	,	2	,	42	,	1524	,	4	)
INSERT INTO PLAYERS VALUES  ('Kuprijanov Anatoly',	1996	,	35	,	1	,	19	,	2183	,	3	)
INSERT INTO PLAYERS VALUES  ('Kusakov Mikhail',	1932	,	51	,	1	,	21	,	1669	,	7	)
INSERT INTO PLAYERS VALUES  ('Lepkov Alexandr',	1974	,	13	,	1	,	107	,	2072	,	3	)
INSERT INTO PLAYERS VALUES  ('Naumova Alexandra',	1961	,	9	,	2	,	10	,	1543	,	3	)
INSERT INTO PLAYERS VALUES  ('Oganisian Semen',	1948	,	32	,	1	,	36	,	1409	,	2	)
INSERT INTO PLAYERS VALUES  ('Oganisian Yury',	1998	,	17	,	1	,	111	,	1714	,	7	)
INSERT INTO PLAYERS VALUES  ('Oganisyan Ovanes',	1951	,	77	,	1	,	25	,	0	,	2	)
INSERT INTO PLAYERS VALUES  ('Orlov Alexandr',	1956	,	29	,	1	,	10	,	1910	,	3	)
INSERT INTO PLAYERS VALUES  ('Orlov Timofey',	1936	,	55	,	1	,	15	,	1629	,	6	)
INSERT INTO PLAYERS VALUES  ('Pantov Dmitriy',	1990	,	14	,	1	,	1	,	0	,	6	)
INSERT INTO PLAYERS VALUES  ('Pereverzev Timofei',	2008	,	61	,	1	,	81	,	1145	,	2	)
INSERT INTO PLAYERS VALUES  ('Reprintsev Alexander',	1941	,	64	,	1	,	108	,	2328	,	6	)
INSERT INTO PLAYERS VALUES  ('Sanzhaev Darsen',	1993	,	53	,	1	,	102	,	2348	,	2	)
INSERT INTO PLAYERS VALUES  ('Semenov Kirill',	1937	,	76	,	1	,	9	,	1964	,	3	)
INSERT INTO PLAYERS VALUES  ('Shmatkov Mikhail',	1986	,	17	,	1	,	50	,	1792	,	5	)
INSERT INTO PLAYERS VALUES  ('Shur Tatiana',	1968	,	45	,	2	,	60	,	1738	,	6	)
INSERT INTO PLAYERS VALUES  ('Shvedchikov Anatoli I.',	1989	,	13	,	1	,	89	,	2333	,	2	)
INSERT INTO PLAYERS VALUES  ('Simakov Alexey P.',	1937	,	18	,	1	,	78	,	2007	,	6	)
INSERT INTO PLAYERS VALUES  ('Skomorokhov Eduard',	1933	,	82	,	1	,	70	,	0	,	1	)
INSERT INTO PLAYERS VALUES  ('Solomin Maxim',	1983	,	12	,	1	,	140	,	1890	,	5	)
INSERT INTO PLAYERS VALUES  ('Travin Vladimir',	1963	,	11	,	1	,	33	,	1813	,	3	)
INSERT INTO PLAYERS VALUES  ('Tsoi Matvey',	1936	,	78	,	1	,	93	,	1420	,	2	)
INSERT INTO PLAYERS VALUES  ('Vasiukova Ekaterina',	1982	,	71	,	2	,	102	,	1754	,	6	)
INSERT INTO PLAYERS VALUES  ('Vorotnikov Vladislav V',	1968	,	31	,	1	,	105	,	2330	,	7	)
INSERT INTO PLAYERS VALUES  ('Vul Arkadi Eremeevich',	1983	,	33	,	1	,	137	,	2160	,	2	)
INSERT INTO PLAYERS VALUES  ('Zagorskii Artem',	1953	,	7	,	1	,	105	,	1495	,	7	)
INSERT INTO PLAYERS VALUES  ('SMITH Shreyas',	2000	,	19	,	1	,	101	,	2168	,	2	)
INSERT INTO PLAYERS VALUES  ('MELLACE Andrew',	1967	,	13	,	1	,	120	,	2116	,	5	)
INSERT INTO PLAYERS VALUES  ('LORNE Ras Malaku',	1954	,	48	,	2	,	41	,	2143	,	4	)
INSERT INTO PLAYERS VALUES  ('GLAVES Raheem',	1992	,	30	,	1	,	35	,	1827	,	5	)
INSERT INTO PLAYERS VALUES  ('JAMES Stuart',	2007	,	85	,	1	,	89	,	1998	,	1	)
INSERT INTO PLAYERS VALUES  ('HINDS Nathan',	1940	,	61	,	1	,	47	,	1876	,	2	)
INSERT INTO PLAYERS VALUES  ('CHRISTIE Joshua',	1982	,	72	,	2	,	63	,	1982	,	7	)
INSERT INTO PLAYERS VALUES  ('RICHARDS-PORTER Deborah',	1995	,	81	,	1	,	111	,	2027	,	3	)
INSERT INTO PLAYERS VALUES  ('JOHNSON Obrian',	2010	,	7	,	1	,	1	,	1539	,	7	)
INSERT INTO PLAYERS VALUES  ('WISDOM Daren',	1984	,	28	,	2	,	54	,	1999	,	1	)
INSERT INTO PLAYERS VALUES  ('BAILEY David',	1946	,	57	,	1	,	70	,	1959	,	3	)
INSERT INTO PLAYERS VALUES  ('BROWN Akeem',	1964	,	73	,	1	,	42	,	2044	,	7	)
INSERT INTO PLAYERS VALUES  ('DIEDRICK Michael',	2006	,	4	,	1	,	134	,	1879	,	5	)
INSERT INTO PLAYERS VALUES  ('MERRITT Kevin',	1940	,	42	,	1	,	70	,	2044	,	4	)
INSERT INTO PLAYERS VALUES  ('CAMPBELL Kevron',	1932	,	5	,	1	,	45	,	1881	,	4	)
INSERT INTO PLAYERS VALUES  ('WILKINSON Ian',	1953	,	83	,	1	,	30	,	1929	,	5	)
INSERT INTO PLAYERS VALUES  ('BELINFANTE Nathan',	1930	,	29	,	1	,	82	,	1667	,	7	)
INSERT INTO PLAYERS VALUES  ('HALL Odane',	1943	,	13	,	1	,	137	,	1765	,	5	)
INSERT INTO PLAYERS VALUES  ('BARRETT Ariel',	1959	,	18	,	2	,	118	,	1704	,	1	)
INSERT INTO PLAYERS VALUES  ('MCDONALD Angelus-Seren',	1938	,	3	,	1	,	110	,	1628	,	2	)
INSERT INTO PLAYERS VALUES  ('ROBINSON Kishane',	1942	,	82	,	1	,	131	,	1395	,	5	)
INSERT INTO PLAYERS VALUES  ('WALKER Lontae',	1942	,	42	,	1	,	17	,	1552	,	5	)
INSERT INTO PLAYERS VALUES  ('LUNGRIN Rashade',	2003	,	3	,	1	,	108	,	1774	,	2	)
INSERT INTO PLAYERS VALUES  ('ROBERTS Rohan',	1996	,	5	,	1	,	130	,	1698	,	2	)
INSERT INTO PLAYERS VALUES  ('WILLIAMS Margoe',	1974	,	43	,	2	,	122	,	1581	,	5	)
INSERT INTO PLAYERS VALUES  ('REID Christopher',	2001	,	10	,	1	,	4	,	1196	,	1	)
INSERT INTO PLAYERS VALUES  ('BARRETT Leighton',	1982	,	62	,	1	,	133	,	1650	,	7	)
INSERT INTO PLAYERS VALUES  ('LYN Christopher',	1991	,	48	,	1	,	101	,	1667	,	6	)
INSERT INTO PLAYERS VALUES  ('BAUMAN James',	1944	,	45	,	1	,	9	,	1878	,	1	)
INSERT INTO PLAYERS VALUES  ('MCDONALD Jhustice-Dimonte',	1990	,	43	,	1	,	67	,	1676	,	1	)
INSERT INTO PLAYERS VALUES  ('SMITH Melisha',	1961	,	67	,	2	,	60	,	1671	,	2	)
INSERT INTO PLAYERS VALUES  ('BAIN Emile',	1936	,	69	,	2	,	3	,	1660	,	3	)
INSERT INTO PLAYERS VALUES  ('LYN Nicholas',	1990	,	63	,	1	,	14	,	1559	,	2	)
INSERT INTO PLAYERS VALUES  ('GUPTE Nikit',	2006	,	25	,	1	,	71	,	1646	,	3	)
INSERT INTO PLAYERS VALUES  ('CLARKE Adani',	2009	,	84	,	1	,	10	,	1636	,	5	)
INSERT INTO PLAYERS VALUES  ('GRAY Krishna',	1996	,	64	,	2	,	45	,	1696	,	5	)
INSERT INTO PLAYERS VALUES  ('THORPE Jaleel',	1932	,	68	,	1	,	110	,	1480	,	6	)
INSERT INTO PLAYERS VALUES  ('RODGERS Andryck',	1955	,	26	,	1	,	120	,	1693	,	1	)
INSERT INTO PLAYERS VALUES  ('YANKANA Alliyah',	1994	,	16	,	1	,	53	,	1427	,	5	)
INSERT INTO PLAYERS VALUES  ('BLACKWOOD Ashanti',	1997	,	86	,	1	,	35	,	1524	,	7	)
INSERT INTO PLAYERS VALUES  ('PORTER Rochelle',	1970	,	79	,	1	,	46	,	1436	,	6	)
INSERT INTO PLAYERS VALUES  ('MCKOY Troy',	2009	,	58	,	1	,	131	,	1553	,	7	)
INSERT INTO PLAYERS VALUES  ('LOBBAN Brandon',	1938	,	70	,	1	,	9	,	1653	,	4	)
INSERT INTO PLAYERS VALUES  ('WALSH Nathan',	1931	,	76	,	1	,	136	,	1448	,	5	)
INSERT INTO PLAYERS VALUES  ('KIDD Aulanni',	1951	,	75	,	1	,	130	,	1472	,	4	)
INSERT INTO PLAYERS VALUES  ('ELLIS Rahjay',	1955	,	26	,	1	,	47	,	1606	,	2	)
INSERT INTO PLAYERS VALUES  ('NASH Démario',	1943	,	14	,	1	,	84	,	1680	,	2	)
INSERT INTO PLAYERS VALUES  ('SHAW Jaden',	2004	,	40	,	1	,	1	,	1389	,	5	)
INSERT INTO PLAYERS VALUES  ('MCKENNIS Darren',	1981	,	7	,	1	,	96	,	1347	,	1	)
INSERT INTO PLAYERS VALUES  ('BENJAMIN Devari',	1940	,	15	,	1	,	3	,	1818	,	6	)
INSERT INTO PLAYERS VALUES  ('CURWIN Nickaylah',	1935	,	50	,	1	,	12	,	1373	,	2	)
INSERT INTO PLAYERS VALUES  ('CHAMBERS Davica',	1969	,	59	,	2	,	106	,	1313	,	2	)
INSERT INTO PLAYERS VALUES  ('BROWN Raehanna',	1938	,	13	,	2	,	127	,	1272	,	7	)
INSERT INTO PLAYERS VALUES  ('BARTLEY Martineil',	1974	,	30	,	1	,	27	,	1099	,	7	)
INSERT INTO PLAYERS VALUES  ('BYFIELD Douglas',	1940	,	12	,	1	,	114	,	1269	,	2	)
INSERT INTO PLAYERS VALUES  ('CAMERON Frederick',	1988	,	64	,	1	,	85	,	1715	,	5	)
INSERT INTO PLAYERS VALUES  ('WRIGHT Zidane',	1975	,	11	,	1	,	13	,	1149	,	3	)
INSERT INTO PLAYERS VALUES  ('CHAI Leah-Ann',	1969	,	43	,	2	,	52	,	1247	,	2	)
INSERT INTO PLAYERS VALUES  ('RAMPAIR Aidan',	1948	,	73	,	1	,	53	,	1354	,	1	)
INSERT INTO PLAYERS VALUES  ('KIDD Deanndra',	1936	,	75	,	1	,	86	,	1213	,	1	)
INSERT INTO PLAYERS VALUES  ('DAVY Damion',	1969	,	86	,	1	,	54	,	2169	,	2	)
INSERT INTO PLAYERS VALUES  ('CURRIAH Malik',	2003	,	24	,	1	,	103	,	1996	,	2	)
INSERT INTO PLAYERS VALUES  ('RICHARDS Shaheem',	1981	,	37	,	2	,	102	,	1573	,	3	)
INSERT INTO PLAYERS VALUES  ('PATMAN Tivon',	1949	,	50	,	1	,	75	,	0	,	6	)
INSERT INTO PLAYERS VALUES  ('CLARKE Kishan',	1953	,	47	,	1	,	135	,	1339	,	7	)
INSERT INTO PLAYERS VALUES  ('FOSTER Deshawn',	1939	,	75	,	1	,	68	,	1201	,	7	)
INSERT INTO PLAYERS VALUES  ('SOARES Andre',	1986	,	11	,	1	,	29	,	1845	,	6	)
INSERT INTO PLAYERS VALUES  ('EDWARDS Dujean',	2011	,	65	,	1	,	63	,	1687	,	3	)
INSERT INTO PLAYERS VALUES  ('SINCLAIR Horace',	1943	,	44	,	1	,	61	,	1908	,	6	)
INSERT INTO PLAYERS VALUES  ('SMITH Annesha',	1948	,	27	,	2	,	140	,	1748	,	7	)
INSERT INTO PLAYERS VALUES  ('Limp Eduardo Thelio',	1950	,	15	,	1	,	61	,	2377	,	6	)
INSERT INTO PLAYERS VALUES  ('Rodi Luis Ernesto',	1987	,	4	,	1	,	102	,	2336	,	6	)
INSERT INTO PLAYERS VALUES  ('Rangel Daniel',	1960	,	83	,	1	,	85	,	2296	,	7	)
INSERT INTO PLAYERS VALUES  ('Cunha Eduardo Arruda Da Gama',	1973	,	19	,	1	,	83	,	2254	,	1	)
INSERT INTO PLAYERS VALUES  ('Costa Carlos Evanir',	1979	,	11	,	1	,	65	,	2218	,	4	)
INSERT INTO PLAYERS VALUES  ('Viana Dirceu',	1945	,	24	,	1	,	1	,	2211	,	6	)
INSERT INTO PLAYERS VALUES  ('De Carvalho Jose Jorge',	1933	,	59	,	1	,	8	,	2199	,	1	)
INSERT INTO PLAYERS VALUES  ('Rios Fo. Hilton Carlos Da Sil',	2002	,	13	,	1	,	112	,	2097	,	5	)
INSERT INTO PLAYERS VALUES  ('Santos Filho Tadeu Sousa',	1974	,	17	,	1	,	140	,	2053	,	6	)
INSERT INTO PLAYERS VALUES  ('Bezerra Natacio Goncalves',	1949	,	18	,	2	,	76	,	1996	,	3	)
INSERT INTO PLAYERS VALUES  ('Manzi Luiz Antonio Bardaro',	1987	,	83	,	1	,	60	,	1995	,	7	)
INSERT INTO PLAYERS VALUES  ('Deus Filho Joaquim De',	1990	,	23	,	1	,	133	,	1966	,	3	)
INSERT INTO PLAYERS VALUES  ('Reis Virginia Lagrange M.',	1939	,	41	,	1	,	5	,	1824	,	6	)
INSERT INTO PLAYERS VALUES  ('Machado Wallace Fernandes',	1934	,	31	,	1	,	7	,	1757	,	2	)
INSERT INTO PLAYERS VALUES  ('Mesquita Arnaldo Leite',	1985	,	80	,	1	,	56	,	1700	,	7	)
INSERT INTO PLAYERS VALUES  ('Rial Antonio Marcos Pinon',	2004	,	8	,	1	,	94	,	1656	,	1	)
INSERT INTO PLAYERS VALUES  ('Da Costa Carlos Henrique Luz',	2010	,	56	,	1	,	16	,	1563	,	4	)
INSERT INTO PLAYERS VALUES  ('Alves Jr Jorge Luiz Barbosa',	1945	,	33	,	1	,	127	,	0	,	2	)
INSERT INTO PLAYERS VALUES  ('Tumiati Eugenio Laginestra',	1996	,	14	,	1	,	98	,	0	,	2	)
INSERT INTO PLAYERS VALUES  ('Romanos Theodoros',	1951	,	21	,	1	,	66	,	2055	,	1	)
INSERT INTO PLAYERS VALUES  ('Prezerakos Dimitrios',	1950	,	54	,	1	,	33	,	1948	,	2	)
INSERT INTO PLAYERS VALUES  ('Giakoustidis Spiros-Avgerinos',	1975	,	25	,	1	,	59	,	1819	,	4	)
INSERT INTO PLAYERS VALUES  ('Mixakis Evangelos',	1937	,	39	,	1	,	68	,	1771	,	1	)
INSERT INTO PLAYERS VALUES  ('Giannopoulos Ioannis',	1988	,	28	,	1	,	107	,	1695	,	5	)
INSERT INTO PLAYERS VALUES  ('Theoharidis Georgios',	1958	,	86	,	1	,	122	,	1680	,	6	)
INSERT INTO PLAYERS VALUES  ('Gountintas Haralabos',	1978	,	55	,	1	,	83	,	1668	,	5	)
INSERT INTO PLAYERS VALUES  ('Fregidis Nikolaos',	1957	,	22	,	1	,	29	,	1640	,	5	)
INSERT INTO PLAYERS VALUES  ('Chrysostomidis Alkiviadis',	2001	,	20	,	1	,	74	,	1626	,	6	)
INSERT INTO PLAYERS VALUES  ('Apostolou Ioannis',	1989	,	29	,	1	,	2	,	1598	,	5	)
INSERT INTO PLAYERS VALUES  ('Avgitidis Isaak',	1942	,	86	,	1	,	63	,	1577	,	4	)
INSERT INTO PLAYERS VALUES  ('Galanis Emmanouil',	1980	,	15	,	1	,	18	,	1552	,	4	)
INSERT INTO PLAYERS VALUES  ('Baltakis Ioannis',	1944	,	35	,	2	,	22	,	1384	,	7	)
INSERT INTO PLAYERS VALUES  ('Giannopoulou Anastasia',	1991	,	82	,	1	,	80	,	1381	,	6	)
INSERT INTO PLAYERS VALUES  ('Doulgerakis Hristos',	1962	,	67	,	1	,	96	,	1372	,	1	)
INSERT INTO PLAYERS VALUES  ('Batsi Lida',	2001	,	86	,	2	,	83	,	1358	,	1	)
INSERT INTO PLAYERS VALUES  ('Kyriakidis Christoforos',	1960	,	47	,	1	,	50	,	1343	,	3	)
INSERT INTO PLAYERS VALUES  ('Zivontsis Dimitrios',	1938	,	62	,	1	,	21	,	1318	,	2	)
INSERT INTO PLAYERS VALUES  ('Katsigris Antonios',	1977	,	81	,	1	,	44	,	1301	,	6	)
INSERT INTO PLAYERS VALUES  ('Zaires Karanasios Konstantino',	2007	,	19	,	1	,	103	,	1300	,	4	)
INSERT INTO PLAYERS VALUES  ('Delidimoudis Konstantinos',	2007	,	75	,	1	,	114	,	1291	,	4	)
INSERT INTO PLAYERS VALUES  ('Tsilidis Christos',	1985	,	6	,	1	,	77	,	1284	,	4	)
INSERT INTO PLAYERS VALUES  ('Magalakis Stefanos',	1985	,	84	,	1	,	41	,	1271	,	6	)
INSERT INTO PLAYERS VALUES  ('Georgas Pavlos',	2006	,	26	,	1	,	52	,	1265	,	4	)
INSERT INTO PLAYERS VALUES  ('Stoimenidis Dimitrios',	2010	,	55	,	1	,	117	,	1258	,	5	)
INSERT INTO PLAYERS VALUES  ('Sampsonoglou Vasilios',	1961	,	78	,	1	,	26	,	1222	,	2	)
INSERT INTO PLAYERS VALUES  ('Markopoulos Ioannis Na',	1991	,	64	,	1	,	62	,	1207	,	6	)
INSERT INTO PLAYERS VALUES  ('Tsaridis Konstantinos',	1993	,	69	,	1	,	98	,	1156	,	3	)
INSERT INTO PLAYERS VALUES  ('Mitsiou Konstantinos',	1977	,	7	,	1	,	96	,	1145	,	1	)
INSERT INTO PLAYERS VALUES  ('Tagkaloglou Savvas Stefanos',	1975	,	56	,	1	,	20	,	1144	,	6	)
INSERT INTO PLAYERS VALUES  ('Asiatidis Ioannis Athanasios',	1961	,	40	,	1	,	41	,	1110	,	6	)
INSERT INTO PLAYERS VALUES  ('Tsivelekidou Anthoula Elpida',	1941	,	20	,	1	,	52	,	1103	,	4	)
INSERT INTO PLAYERS VALUES  ('Petlis Evangelos',	1970	,	64	,	1	,	43	,	1097	,	4	)
INSERT INTO PLAYERS VALUES  ('Mitsiou Georgios',	1945	,	52	,	1	,	106	,	1096	,	1	)
INSERT INTO PLAYERS VALUES  ('Tsakona Maria',	2003	,	24	,	2	,	135	,	1075	,	5	)
INSERT INTO PLAYERS VALUES  ('Kotzamani Fani-Maria',	2010	,	59	,	2	,	107	,	1063	,	5	)
INSERT INTO PLAYERS VALUES  ('Karamichos Michail',	1987	,	77	,	1	,	2	,	1050	,	2	)
INSERT INTO PLAYERS VALUES  ('Kyparissopoulos Spyridon',	1979	,	51	,	1	,	34	,	1032	,	5	)
INSERT INTO PLAYERS VALUES  ('Kotsailidis Pavlos',	1984	,	56	,	1	,	118	,	1030	,	2	)
INSERT INTO PLAYERS VALUES  ('Vafeiadakis Konstantinos',	1945	,	19	,	1	,	102	,	1009	,	3	)
INSERT INTO PLAYERS VALUES  ('Kyparissopoulos Nikolaos',	1931	,	42	,	1	,	122	,	940	,	6	)
INSERT INTO PLAYERS VALUES  ('Karakotsios Konstantinos',	1999	,	2	,	1	,	112	,	912	,	1	)
INSERT INTO PLAYERS VALUES  ('Balafoutas Alexandros',	1943	,	39	,	1	,	74	,	830	,	3	)
INSERT INTO PLAYERS VALUES  ('Stoimenidis Markos',	1942	,	71	,	1	,	110	,	830	,	7	)
INSERT INTO PLAYERS VALUES  ('Vafeiadakis Petros',	1962	,	18	,	1	,	77	,	830	,	3	)
INSERT INTO PLAYERS VALUES  ('Balafoutas Dimitrios',	1980	,	3	,	1	,	59	,	0	,	7	)
INSERT INTO PLAYERS VALUES  ('Delisavidis Dionysios',	1973	,	48	,	1	,	39	,	0	,	1	)
INSERT INTO PLAYERS VALUES  ('Giakoustidou Evgenia',	2010	,	27	,	2	,	53	,	0	,	5	)
INSERT INTO PLAYERS VALUES  ('Karakotsios Loukas Georgios',	1989	,	61	,	1	,	49	,	0	,	5	)
INSERT INTO PLAYERS VALUES  ('Machairidis Grigorios',	1944	,	32	,	1	,	64	,	0	,	2	)
INSERT INTO PLAYERS VALUES  ('Mavridis Achileas',	1955	,	34	,	1	,	6	,	0	,	4	)
INSERT INTO PLAYERS VALUES  ('Michalitsis Posidon',	1995	,	33	,	1	,	73	,	0	,	6	)
INSERT INTO PLAYERS VALUES  ('Mitsiou Anna Maria',	1962	,	61	,	2	,	112	,	0	,	5	)
INSERT INTO PLAYERS VALUES  ('Mpitzios Evaggelos',	1950	,	15	,	1	,	24	,	0	,	6	)
INSERT INTO PLAYERS VALUES  ('Steiakakis Konstantinos',	2000	,	25	,	1	,	125	,	0	,	5	)
INSERT INTO PLAYERS VALUES  ('Toptsidis Pavlos',	1977	,	16	,	1	,	129	,	0	,	5	)
INSERT INTO PLAYERS VALUES  ('Tsakonas Konstantinos',	1976	,	57	,	1	,	132	,	0	,	4	)




INSERT INTO [TOURMAMENTS] VALUES  ('Berndorfer Kinderschachturnier 2017',	1	,	1	,	86	,'20101018','20101030')
INSERT INTO [TOURMAMENTS] VALUES  ('BLITZ PIALA MERDEKA',	1	,	3	,	45	,'20090524','20090604')
INSERT INTO [TOURMAMENTS] VALUES  ('Campionatul National pe echipe-DIVIZIA A',	2	,	1	,	52	,'20051107','20060127')
INSERT INTO [TOURMAMENTS] VALUES  ('Classico FESMAX RAPID',	1	,	2	,	56	,'20010515','20010630')
INSERT INTO [TOURMAMENTS] VALUES  ('LIGHTHOUSE INTERSCHOOLS CHESS TOURNAMENT',	3	,	1	,	25	,'20000801','20000819')




INSERT INTO [PARTICIPATIONS] VALUES (	1	,	141	,	1	,	13	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	142	,	2	,	22	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	143	,	3	,	7	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	144	,	4	,	14	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	145	,	5	,	4	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	146	,	6	,	47	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	147	,	7	,	28	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	148	,	8	,	50	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	149	,	9	,	39	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	150	,	10	,	38	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	151	,	11	,	32	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	152	,	12	,	19	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	153	,	13	,	30	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	154	,	14	,	25	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	155	,	15	,	5	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	156	,	16	,	26	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	157	,	17	,	8	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	158	,	18	,	45	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	159	,	19	,	18	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	160	,	20	,	12	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	161	,	21	,	42	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	162	,	22	,	33	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	163	,	23	,	2	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	164	,	24	,	37	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	165	,	25	,	46	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	166	,	26	,	40	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	167	,	27	,	16	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	168	,	28	,	6	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	169	,	29	,	29	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	170	,	30	,	41	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	171	,	31	,	48	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	172	,	32	,	44	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	173	,	33	,	17	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	174	,	34	,	1	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	175	,	35	,	15	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	176	,	36	,	23	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	177	,	37	,	20	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	178	,	38	,	24	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	179	,	39	,	35	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	180	,	40	,	11	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	181	,	41	,	34	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	182	,	42	,	3	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	183	,	43	,	49	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	184	,	44	,	27	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	185	,	45	,	21	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	186	,	46	,	43	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	187	,	47	,	36	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	188	,	48	,	31	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	189	,	49	,	10	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	1	,	190	,	50	,	9	,	1	)
										
										
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	100	,	1	,	29	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	101	,	2	,	39	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	102	,	3	,	28	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	103	,	4	,	6	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	104	,	5	,	37	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	105	,	6	,	31	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	106	,	7	,	10	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	107	,	8	,	25	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	108	,	9	,	7	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	109	,	10	,	27	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	110	,	11	,	20	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	111	,	12	,	34	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	112	,	13	,	33	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	113	,	14	,	4	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	114	,	15	,	12	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	115	,	16	,	14	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	116	,	17	,	30	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	117	,	18	,	1	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	118	,	19	,	5	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	119	,	20	,	38	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	120	,	21	,	36	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	121	,	22	,	32	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	122	,	23	,	22	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	123	,	24	,	16	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	124	,	25	,	11	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	125	,	26	,	35	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	126	,	27	,	23	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	127	,	28	,	13	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	128	,	29	,	17	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	129	,	30	,	2	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	130	,	31	,	3	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	131	,	32	,	24	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	132	,	33	,	21	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	133	,	34	,	8	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	134	,	35	,	15	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	135	,	36	,	40	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	136	,	37	,	26	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	137	,	38	,	41	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	138	,	39	,	18	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	139	,	40	,	19	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	2	,	140	,	41	,	9	,	1	)
										
										
INSERT INTO [PARTICIPATIONS] VALUES (	3	,	91	,	1	,	5	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	3	,	92	,	2	,	4	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	3	,	93	,	3	,	8	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	3	,	94	,	4	,	10	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	3	,	95	,	5	,	9	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	3	,	96	,	6	,	2	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	3	,	97	,	7	,	3	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	3	,	98	,	8	,	7	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	3	,	99	,	9	,	1	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	3	,	100	,	10	,	6	,	1	)
										
										
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	42	,	1	,	38	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	43	,	2	,	24	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	44	,	3	,	45	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	45	,	4	,	1	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	46	,	5	,	7	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	47	,	6	,	14	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	48	,	7	,	23	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	49	,	8	,	13	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	50	,	9	,	43	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	51	,	10	,	17	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	52	,	11	,	27	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	53	,	12	,	6	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	54	,	13	,	31	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	55	,	14	,	32	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	56	,	15	,	16	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	57	,	16	,	29	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	58	,	17	,	33	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	59	,	18	,	39	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	60	,	19	,	48	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	61	,	20	,	41	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	62	,	21	,	47	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	63	,	22	,	30	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	64	,	23	,	42	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	65	,	24	,	3	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	66	,	25	,	25	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	67	,	26	,	21	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	68	,	27	,	20	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	69	,	28	,	40	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	70	,	29	,	12	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	71	,	30	,	35	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	72	,	31	,	9	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	73	,	32	,	2	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	74	,	33	,	49	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	75	,	34	,	46	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	76	,	35	,	36	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	77	,	36	,	44	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	78	,	37	,	8	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	79	,	38	,	11	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	80	,	39	,	28	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	81	,	40	,	18	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	82	,	41	,	37	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	83	,	42	,	22	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	84	,	43	,	4	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	85	,	44	,	5	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	86	,	45	,	26	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	87	,	46	,	10	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	88	,	47	,	15	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	89	,	48	,	19	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	4	,	90	,	49	,	34	,	1	)
										
										
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	2	,	1	,	34	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	3	,	2	,	7	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	4	,	3	,	11	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	5	,	4	,	27	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	6	,	5	,	10	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	7	,	6	,	24	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	8	,	7	,	15	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	9	,	8	,	35	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	10	,	9	,	12	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	11	,	10	,	19	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	12	,	11	,	5	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	13	,	12	,	32	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	14	,	13	,	18	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	15	,	14	,	16	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	16	,	15	,	31	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	17	,	16	,	21	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	18	,	17	,	1	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	19	,	18	,	38	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	20	,	19	,	14	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	21	,	20	,	6	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	22	,	21	,	23	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	23	,	22	,	30	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	24	,	23	,	28	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	25	,	24	,	17	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	26	,	25	,	8	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	27	,	26	,	9	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	28	,	27	,	20	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	29	,	28	,	4	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	30	,	29	,	2	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	31	,	30	,	22	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	32	,	31	,	29	,	0	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	33	,	32	,	33	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	34	,	33	,	3	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	35	,	34	,	37	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	36	,	35	,	13	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	37	,	36	,	26	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	38	,	37	,	25	,	1	)
INSERT INTO [PARTICIPATIONS] VALUES (	5	,	39	,	38	,	36	,	1	)




INSERT INTO [GAMES] VALUES (	5	,	2	,	10	,	1	,	1	)
INSERT INTO [GAMES] VALUES (	5	,	3	,	11	,	1	,	1	)
INSERT INTO [GAMES] VALUES (	5	,	4	,	12	,	0	,	1	)
INSERT INTO [GAMES] VALUES (	5	,	5	,	13	,	0	,	1	)
INSERT INTO [GAMES] VALUES (	5	,	6	,	14	,	1	,	1	)
INSERT INTO [GAMES] VALUES (	5	,	7	,	15	,	0	,	1	)
INSERT INTO [GAMES] VALUES (	5	,	8	,	16	,	1	,	1	)
INSERT INTO [GAMES] VALUES (	5	,	9	,	17	,	0	,	1	)
INSERT INTO [GAMES] VALUES (	5	,	2	,	3	,	1	,	2	)
INSERT INTO [GAMES] VALUES (	5	,	12	,	13	,	0	,	2	)
INSERT INTO [GAMES] VALUES (	5	,	6	,	15	,	0	,	2	)
INSERT INTO [GAMES] VALUES (	5	,	8	,	17	,	1	,	2	)
INSERT INTO [GAMES] VALUES (	5	,	2	,	13	,	0	,	3	)
INSERT INTO [GAMES] VALUES (	5	,	15	,	17	,	1	,	3	)
INSERT INTO [GAMES] VALUES (	5	,	13	,	15	,	1	,	4	)




INSERT INTO [GAMES] VALUES (	4	,	42	,	50	,	1	,	1	)
INSERT INTO [GAMES] VALUES (	4	,	43	,	51	,	1	,	1	)
INSERT INTO [GAMES] VALUES (	4	,	44	,	52	,	1	,	1	)
INSERT INTO [GAMES] VALUES (	4	,	45	,	53	,	0	,	1	)
INSERT INTO [GAMES] VALUES (	4	,	46	,	54	,	0.5	,	1	)
INSERT INTO [GAMES] VALUES (	4	,	47	,	55	,	0	,	1	)
INSERT INTO [GAMES] VALUES (	4	,	48	,	56	,	1	,	1	)
INSERT INTO [GAMES] VALUES (	4	,	49	,	57	,	0.5	,	1	)
			
INSERT INTO [GAMES] VALUES (	4	,	50	,	45	,	0.5	,	2	)
INSERT INTO [GAMES] VALUES (	4	,	51	,	56	,	1	,	2	)
INSERT INTO [GAMES] VALUES (	4	,	52	,	47	,	0	,	2	)
INSERT INTO [GAMES] VALUES (	4	,	42	,	44	,	0.5	,	2	)
INSERT INTO [GAMES] VALUES (	4	,	43	,	48	,	0.5	,	2	)
INSERT INTO [GAMES] VALUES (	4	,	53	,	55	,	0	,	2	)
INSERT INTO [GAMES] VALUES (	4	,	57	,	46	,	1	,	2	)
INSERT INTO [GAMES] VALUES (	4	,	54	,	49	,	0.5	,	2	)
										
INSERT INTO [GAMES] VALUES (	4	,	47	,	51	,	0.5	,	3	)
INSERT INTO [GAMES] VALUES (	4	,	55	,	57	,	0	,	3	)
INSERT INTO [GAMES] VALUES (	4	,	48	,	42	,	0	,	3	)
INSERT INTO [GAMES] VALUES (	4	,	44	,	43	,	0	,	3	)
INSERT INTO [GAMES] VALUES (	4	,	45	,	54	,	1	,	3	)
INSERT INTO [GAMES] VALUES (	4	,	49	,	50	,	0	,	3	)
INSERT INTO [GAMES] VALUES (	4	,	56	,	52	,	0.5	,	3	)
INSERT INTO [GAMES] VALUES (	4	,	46	,	53	,	0	,	3	)
										
										
INSERT INTO [GAMES] VALUES (	4	,	57	,	42	,	0.5	,	4	)
INSERT INTO [GAMES] VALUES (	4	,	43	,	45	,	0.5	,	4	)
INSERT INTO [GAMES] VALUES (	4	,	50	,	53	,	1	,	4	)
INSERT INTO [GAMES] VALUES (	4	,	48	,	55	,	1	,	4	)
INSERT INTO [GAMES] VALUES (	4	,	54	,	44	,	1	,	4	)
INSERT INTO [GAMES] VALUES (	4	,	49	,	46	,	0.5	,	4	)
INSERT INTO [GAMES] VALUES (	4	,	52	,	47	,	0	,	4	)
INSERT INTO [GAMES] VALUES (	4	,	56	,	51	,	1	,	4	)



INSERT INTO [GAMES] VALUES (	3	,	91	,	92	,	0.5	,	1	)
INSERT INTO [GAMES] VALUES (	3	,	91	,	93	,	0.5	,	1	)
INSERT INTO [GAMES] VALUES (	3	,	91	,	94	,	0	,	1	)
INSERT INTO [GAMES] VALUES (	3	,	91	,	95	,	0	,	1	)
INSERT INTO [GAMES] VALUES (	3	,	91	,	96	,	0	,	1	)
INSERT INTO [GAMES] VALUES (	3	,	91	,	97	,	0	,	1	)
INSERT INTO [GAMES] VALUES (	3	,	91	,	98	,	1	,	1	)
INSERT INTO [GAMES] VALUES (	3	,	91	,	99	,	0	,	1	)
INSERT INTO [GAMES] VALUES (	3	,	91	,	100	,	0.5	,	1	)
INSERT INTO [GAMES] VALUES (	3	,	92	,	91	,	0.5	,	1	)
INSERT INTO [GAMES] VALUES (	3	,	92	,	93	,	0	,	2	)
INSERT INTO [GAMES] VALUES (	3	,	92	,	94	,	1	,	2	)
INSERT INTO [GAMES] VALUES (	3	,	92	,	95	,	0.5	,	2	)
INSERT INTO [GAMES] VALUES (	3	,	92	,	96	,	1	,	2	)
INSERT INTO [GAMES] VALUES (	3	,	92	,	97	,	1	,	2	)
INSERT INTO [GAMES] VALUES (	3	,	92	,	98	,	0	,	2	)
INSERT INTO [GAMES] VALUES (	3	,	92	,	99	,	0.5	,	2	)
INSERT INTO [GAMES] VALUES (	3	,	92	,	100	,	1	,	2	)
INSERT INTO [GAMES] VALUES (	3	,	93	,	91	,	0	,	2	)
INSERT INTO [GAMES] VALUES (	3	,	93	,	92	,	1	,	2	)
INSERT INTO [GAMES] VALUES (	3	,	93	,	94	,	0	,	3	)
INSERT INTO [GAMES] VALUES (	3	,	93	,	95	,	0.5	,	3	)
INSERT INTO [GAMES] VALUES (	3	,	93	,	96	,	0.5	,	3	)
INSERT INTO [GAMES] VALUES (	3	,	93	,	97	,	0.5	,	3	)
INSERT INTO [GAMES] VALUES (	3	,	93	,	98	,	1	,	3	)
INSERT INTO [GAMES] VALUES (	3	,	93	,	99	,	0.5	,	3	)
INSERT INTO [GAMES] VALUES (	3	,	93	,	100	,	0.5	,	3	)
INSERT INTO [GAMES] VALUES (	3	,	94	,	91	,	0	,	3	)
INSERT INTO [GAMES] VALUES (	3	,	94	,	92	,	0.5	,	3	)
INSERT INTO [GAMES] VALUES (	3	,	94	,	93	,	0.5	,	3	)
INSERT INTO [GAMES] VALUES (	3	,	94	,	95	,	0.5	,	4	)
INSERT INTO [GAMES] VALUES (	3	,	94	,	96	,	1	,	4	)
INSERT INTO [GAMES] VALUES (	3	,	94	,	97	,	0.5	,	4	)
INSERT INTO [GAMES] VALUES (	3	,	94	,	98	,	1	,	4	)
INSERT INTO [GAMES] VALUES (	3	,	94	,	99	,	1	,	4	)
INSERT INTO [GAMES] VALUES (	3	,	94	,	100	,	1	,	4	)
INSERT INTO [GAMES] VALUES (	3	,	95	,	91	,	0.5	,	4	)
INSERT INTO [GAMES] VALUES (	3	,	95	,	92	,	0.5	,	4	)
INSERT INTO [GAMES] VALUES (	3	,	95	,	93	,	0	,	4	)
INSERT INTO [GAMES] VALUES (	3	,	95	,	94	,	0.5	,	4	)
INSERT INTO [GAMES] VALUES (	3	,	95	,	96	,	1	,	5	)
INSERT INTO [GAMES] VALUES (	3	,	95	,	97	,	1	,	5	)
INSERT INTO [GAMES] VALUES (	3	,	95	,	98	,	0	,	5	)
INSERT INTO [GAMES] VALUES (	3	,	95	,	99	,	0.5	,	5	)
INSERT INTO [GAMES] VALUES (	3	,	95	,	100	,	0.5	,	5	)
INSERT INTO [GAMES] VALUES (	3	,	96	,	91	,	0.5	,	5	)
INSERT INTO [GAMES] VALUES (	3	,	96	,	92	,	1	,	5	)
INSERT INTO [GAMES] VALUES (	3	,	96	,	93	,	0.5	,	5	)
INSERT INTO [GAMES] VALUES (	3	,	96	,	94	,	0	,	5	)
INSERT INTO [GAMES] VALUES (	3	,	96	,	95	,	0	,	5	)
INSERT INTO [GAMES] VALUES (	3	,	96	,	97	,	0	,	6	)
INSERT INTO [GAMES] VALUES (	3	,	96	,	98	,	0	,	6	)
INSERT INTO [GAMES] VALUES (	3	,	96	,	99	,	0.5	,	6	)
INSERT INTO [GAMES] VALUES (	3	,	96	,	100	,	1	,	6	)
INSERT INTO [GAMES] VALUES (	3	,	97	,	91	,	0	,	6	)
INSERT INTO [GAMES] VALUES (	3	,	97	,	92	,	1	,	6	)
INSERT INTO [GAMES] VALUES (	3	,	97	,	93	,	1	,	6	)
INSERT INTO [GAMES] VALUES (	3	,	97	,	94	,	1	,	6	)
INSERT INTO [GAMES] VALUES (	3	,	97	,	95	,	0	,	6	)
INSERT INTO [GAMES] VALUES (	3	,	97	,	96	,	1	,	6	)
INSERT INTO [GAMES] VALUES (	3	,	97	,	98	,	0.5	,	7	)
INSERT INTO [GAMES] VALUES (	3	,	97	,	99	,	1	,	7	)
INSERT INTO [GAMES] VALUES (	3	,	97	,	100	,	0.5	,	7	)
INSERT INTO [GAMES] VALUES (	3	,	98	,	91	,	0	,	7	)
INSERT INTO [GAMES] VALUES (	3	,	98	,	92	,	1	,	7	)
INSERT INTO [GAMES] VALUES (	3	,	98	,	93	,	0.5	,	7	)
INSERT INTO [GAMES] VALUES (	3	,	98	,	94	,	0	,	7	)
INSERT INTO [GAMES] VALUES (	3	,	98	,	95	,	0.5	,	7	)
INSERT INTO [GAMES] VALUES (	3	,	98	,	96	,	0	,	7	)
INSERT INTO [GAMES] VALUES (	3	,	98	,	97	,	0	,	7	)
INSERT INTO [GAMES] VALUES (	3	,	98	,	99	,	1	,	8	)
INSERT INTO [GAMES] VALUES (	3	,	98	,	100	,	1	,	8	)
INSERT INTO [GAMES] VALUES (	3	,	99	,	91	,	0.5	,	8	)
INSERT INTO [GAMES] VALUES (	3	,	99	,	92	,	0.5	,	8	)
INSERT INTO [GAMES] VALUES (	3	,	99	,	93	,	1	,	8	)
INSERT INTO [GAMES] VALUES (	3	,	99	,	94	,	0.5	,	8	)
INSERT INTO [GAMES] VALUES (	3	,	99	,	95	,	0.5	,	8	)
INSERT INTO [GAMES] VALUES (	3	,	99	,	96	,	0	,	8	)
INSERT INTO [GAMES] VALUES (	3	,	99	,	97	,	1	,	8	)
INSERT INTO [GAMES] VALUES (	3	,	99	,	98	,	0.5	,	8	)
INSERT INTO [GAMES] VALUES (	3	,	99	,	100	,	1	,	9	)
INSERT INTO [GAMES] VALUES (	3	,	100	,	91	,	0	,	9	)
INSERT INTO [GAMES] VALUES (	3	,	100	,	92	,	1	,	9	)
INSERT INTO [GAMES] VALUES (	3	,	100	,	93	,	0.5	,	9	)
INSERT INTO [GAMES] VALUES (	3	,	100	,	94	,	0	,	9	)
INSERT INTO [GAMES] VALUES (	3	,	100	,	95	,	0.5	,	9	)
INSERT INTO [GAMES] VALUES (	3	,	100	,	96	,	0	,	9	)
INSERT INTO [GAMES] VALUES (	3	,	100	,	97	,	1	,	9	)
INSERT INTO [GAMES] VALUES (	3	,	100	,	98	,	1	,	9	)
INSERT INTO [GAMES] VALUES (	3	,	100	,	99	,	1	,	9	)





INSERT INTO [GAME_DESCRIPTION] VALUES (	1	,	1	,	17	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	1	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	1	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	2	,	1	,	52	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	2	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	2	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	3	,	1	,	54	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	3	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	3	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	4	,	1	,	16	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	4	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	4	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	5	,	1	,	121	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	5	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	5	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	6	,	1	,	41	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	6	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	6	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	7	,	1	,	140	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	7	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	7	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	8	,	1	,	41	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	8	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	8	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	9	,	1	,	156	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	9	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	9	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	10	,	1	,	32	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	10	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	10	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	11	,	1	,	137	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	11	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	11	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	12	,	1	,	17	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	12	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	12	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	13	,	1	,	62	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	13	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	13	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	14	,	1	,	139	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	14	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	14	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	15	,	1	,	100	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	15	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	15	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	16	,	1	,	60	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	16	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	16	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	17	,	1	,	1	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	17	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	17	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	18	,	1	,	150	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	18	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	18	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	19	,	1	,	76	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	19	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	19	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	20	,	1	,	22	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	20	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	20	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	21	,	1	,	153	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	21	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	21	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	22	,	1	,	139	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	22	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	22	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	23	,	1	,	87	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	23	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	23	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	24	,	1	,	153	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	24	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	24	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	25	,	1	,	20	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	25	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	25	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	26	,	1	,	8	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	26	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	26	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	27	,	1	,	90	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	27	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	27	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	28	,	1	,	40	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	28	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	28	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	29	,	1	,	4	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	29	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	29	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	30	,	1	,	23	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	30	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	30	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	31	,	1	,	118	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	31	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	31	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	32	,	1	,	17	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	32	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	32	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	33	,	1	,	129	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	33	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	33	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	34	,	1	,	107	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	34	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	34	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	35	,	1	,	123	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	35	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	35	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	36	,	1	,	97	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	36	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	36	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	37	,	1	,	51	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	37	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	37	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	38	,	1	,	82	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	38	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	38	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	39	,	1	,	82	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	39	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	39	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	40	,	1	,	135	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	40	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	40	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	41	,	1	,	99	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	41	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	41	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	42	,	1	,	73	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	42	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	42	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	43	,	1	,	38	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	43	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	43	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	44	,	1	,	142	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	44	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	44	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	45	,	1	,	122	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	45	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	45	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	46	,	1	,	113	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	46	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	46	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	47	,	1	,	44	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	47	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	47	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	48	,	1	,	84	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	48	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	48	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	49	,	1	,	98	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	49	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	49	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	50	,	1	,	98	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	50	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	50	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	51	,	1	,	53	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	51	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	51	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	52	,	1	,	42	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	52	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	52	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	53	,	1	,	18	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	53	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	53	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	54	,	1	,	151	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	54	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	54	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	55	,	1	,	73	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	55	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	55	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	56	,	1	,	54	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	56	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	56	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	57	,	1	,	146	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	57	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	57	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	58	,	1	,	120	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	58	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	58	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	59	,	1	,	34	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	59	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	59	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	60	,	1	,	136	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	60	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	60	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	61	,	1	,	142	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	61	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	61	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	62	,	1	,	144	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	62	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	62	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	63	,	1	,	154	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	63	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	63	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	64	,	1	,	59	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	64	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	64	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	65	,	1	,	58	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	65	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	65	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	66	,	1	,	43	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	66	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	66	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	67	,	1	,	152	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	67	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	67	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	68	,	1	,	4	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	68	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	68	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	69	,	1	,	145	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	69	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	69	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	70	,	1	,	69	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	70	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	70	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	71	,	1	,	129	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	71	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	71	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	72	,	1	,	127	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	72	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	72	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	73	,	1	,	60	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	73	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	73	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	74	,	1	,	148	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	74	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	74	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	75	,	1	,	131	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	75	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	75	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	76	,	1	,	18	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	76	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	76	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	77	,	1	,	66	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	77	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	77	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	78	,	1	,	31	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	78	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	78	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	79	,	1	,	79	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	79	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	79	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	80	,	1	,	101	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	80	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	80	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	81	,	1	,	139	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	81	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	81	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	82	,	1	,	138	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	82	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	82	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	83	,	1	,	104	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	83	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	83	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	84	,	1	,	43	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	84	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	84	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	85	,	1	,	86	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	85	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	85	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	86	,	1	,	41	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	86	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	86	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	87	,	1	,	95	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	87	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	87	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	88	,	1	,	17	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	88	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	88	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	89	,	1	,	146	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	89	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	89	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	90	,	1	,	144	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	90	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	90	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	91	,	1	,	131	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	91	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	91	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	92	,	1	,	133	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	92	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	92	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	93	,	1	,	121	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	93	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	93	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	94	,	1	,	128	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	94	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	94	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	95	,	1	,	3	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	95	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	95	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	96	,	1	,	79	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	96	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	96	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	97	,	1	,	102	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	97	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	97	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	98	,	1	,	125	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	98	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	98	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	99	,	1	,	130	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	99	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	99	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	100	,	1	,	55	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	100	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	100	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	101	,	1	,	3	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	101	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	101	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	102	,	1	,	13	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	102	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	102	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	103	,	1	,	152	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	103	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	103	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	104	,	1	,	17	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	104	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	104	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	105	,	1	,	20	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	105	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	105	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	106	,	1	,	53	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	106	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	106	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	107	,	1	,	10	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	107	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	107	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	108	,	1	,	77	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	108	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	108	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	109	,	1	,	76	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	109	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	109	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	110	,	1	,	60	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	110	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	110	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	111	,	1	,	43	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	111	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	111	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	112	,	1	,	13	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	112	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	112	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	113	,	1	,	91	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	113	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	113	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	114	,	1	,	140	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	114	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	114	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	115	,	1	,	140	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	115	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	115	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	116	,	1	,	71	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	116	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	116	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	117	,	1	,	126	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	117	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	117	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	118	,	1	,	105	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	118	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	118	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	119	,	1	,	147	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	119	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	119	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	120	,	1	,	29	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	120	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	120	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	121	,	1	,	72	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	121	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	121	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	122	,	1	,	109	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	122	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	122	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	123	,	1	,	37	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	123	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	123	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	124	,	1	,	105	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	124	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	124	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	125	,	1	,	23	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	125	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	125	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	126	,	1	,	8	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	126	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	126	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	127	,	1	,	50	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	127	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	127	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	128	,	1	,	70	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	128	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	128	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	129	,	1	,	93	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	129	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	129	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	130	,	1	,	75	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	130	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	130	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	131	,	1	,	35	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	131	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	131	,	3	,	162	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	132	,	1	,	50	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	132	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	132	,	3	,	164	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	133	,	1	,	41	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	133	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	133	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	134	,	1	,	108	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	134	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	134	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	135	,	1	,	43	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	135	,	2	,	157	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	135	,	3	,	163	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	136	,	1	,	82	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	136	,	2	,	158	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	136	,	3	,	161	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	137	,	1	,	99	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	137	,	2	,	159	)
INSERT INTO [GAME_DESCRIPTION] VALUES (	137	,	3	,	164	)



-- dbcc checkident ([PARTICIPATIONS], reseed,0)
-- delete [PARTICIPATIONS]
 
--select * from COUNTRIES;
--select * from [GAME_DESCRIPTION];




--create table stolbet (
--kirillita varchar(100) COLLATE Cyrillic_General_CI_AS)
 
 

